### ISSUE TITLE
Ctrl+X not working in nano

### ISSUE THREAD

**Issue by WoodyWoodsta** [zeit/hyper#1069]
- **OS version and name**: elementary OS Loki
- **Hyper.app version**: @https://github.com/zeit/hyper/commit/e31f975f788f3ced0175c5cffd203690d99c350c
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/WoodyWoodsta/722486e90139eba0138aa0df82140296
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla
## Issue

As of https://github.com/zeit/hyper/commit/be286c0d5aaa14528112213c9be3201384d2dcfa, <kbd>Ctrl</kbd>+<kbd>X</kbd> does not work in nano, since it is being caught by hyper for the cut command. I'm sure this may be one of many conflicting keyboard shortcuts. Perhaps a way to temporarily bypass the hyper accelerators would help for these cases.

**Comment by ThePooE** [comment]
For the reference, https://github.com/zeit/hyper/commit/a8b17e6322622adb4a5e86911f006225fb8f6eac still works with macOS using <kbd>CTRL</kbd> + <kbd>X</kbd> to quit the nano

**Comment by newgene** [comment]
I noticed that "CTRL+SHIFT+x" actually work for nano, in replace of "CTRL+x".

**Comment by radicaled** [comment]
Gnome Terminal has copy/paste keybindings set as "SHIFT+CTRL+X" and "SHIFT+CTRL+V" instead of CTRL+X/CTRL+V. On further inspection, every every commonly used short-cut in Gnome Terminal is prefixed with "SHIFT" to avoid conflicts with terminal applications that use the same keystrokes. Maybe that's the solution/convention Hyper should adopt for Linux?

**Comment by perry-mitchell** [comment]
For reference, this is still an issue on the 1.0.0 release..

**Comment by Seldaek** [comment]
FWIW and because nobody mentioned it, the exact same problem exists on Windows as it also uses `CTRL+*` command bindings unlike OS X.

The best way forward I suppose would be to prefix Hyper-key bindings with CTRL+SHIFT rather than simple CTRL, or to add bindings configurability in the user config, so that users can remove all the unneeded shortcuts and/or rebind conflicting ones.

**Comment by WoodyWoodsta** [comment]
I know that some of the key-bindings already use <kbd>Shift</kbd> and so it might be a little tricky. I was happy with the <kbd>Ctrl</kbd>+<kbd>Super</kbd> (or <kbd>Win-key</kbd>) as it was before. Perhaps this is grounds for a plugin that can switch between common sets of key-bindings found in other popular terminals.

**Comment by perry-mitchell** [comment]
@WoodyWoodsta has a good point, though I would almost see the **re-assignment** of such highly-used shortcuts as a high-priority compared to supporting custom keybindings.

<kbd>Ctrl</kbd>+<kbd>x</kbd> is assigned to Cut, but the question is do more people use the Cut-shortcut than those who use nano and want to exit in the default (and displayed) way? What's more confounding is that <kbd>Ctrl</kbd>+<kbd>k</kbd> is assigned to "Clear" in Hyper, but this would act as Cut in nano... 😞

**Comment by dfroze** [comment]
Hy, just started to play with this app. A quick question regarding this subjec, is there a way to change the shortcuts in hyper? It will be great if we could customize these shortcuts.

**Comment by nbolten** [comment]
Hi, I've put in a pull request that hopefully addresses this issue here: https://github.com/zeit/hyper/pull/1191 . It would make the default `mod` key into <kbd>Ctrl</kbd>+<kbd>Shift</kbd> on Windows and Linux so that there are no longer conflicts with CLI apps using <kbd>Ctrl</kbd> shortcuts.

It does not make the `mod` key configurable in `hyper.js`, but I think there's another patch in the works for that.

Feedback is helpful! The pull request is surely not perfect.

**Comment by alexellis** [comment]
+1 this is an odd experience - for instance Control + W should cut back one word, but keeps closing my terminal. What's the best way to fix the bindings?

**Comment by taylorthurlow** [comment]
Chiming in to agree that something should be done to preserve the `ctrl+w` shortcut.

**Comment by ppot** [comment]
@taylorthurlow #1509 Already address this.

**Comment by taylorthurlow** [comment]
@ppot Ah didn't think to check that. Glad to hear, thanks!

**Comment by ppot** [comment]
@taylorthurlow Nothing for!

**Comment by ppot** [comment]
close in #1876

**Comment by jancborchardt** [comment]
Thanks a lot @ppot! :)
