### ISSUE TITLE
Russian symbols display uncorrect

### ISSUE THREAD

**Issue by skad0** [zeit/hyper#1070]
- **OS version and name**: macOS Sierra 10.12.1
- **Hyper.app version**: 0.8.3
- **config file .hyper.js**: [here](https://gist.github.com/skad0/7f607b875c8b8840cb7f2f38f9561ae1)
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue
When i'm trying to type russian symbols, i get some weird effect like on screenshot:
![Screenshot](https://cloud.githubusercontent.com/assets/974119/20833667/e253b98c-b8a1-11e6-87e6-5cffca63458c.png)

**Comment by matheuss** [comment]
@skad0 which characters were you trying to display?

**Comment by skad0** [comment]
>@skad0 which characters were you trying to display?

Any from russian alphabet. For example: `абвгд`

**Comment by matheuss** [comment]
@skad0 this was fixed by #1006 🎉 

![screen shot 2016-12-02 at 11 26 09 am](https://cloud.githubusercontent.com/assets/4721750/20835513/2e26bb5e-b882-11e6-8a68-8ebb534fe16e.png)
We'll ship it very 🔜 👌 

PS: **thank you very much** for your issue – it showed me that I introduced a [regression] on #1058 🙌 

[regression]: https://github.com/zeit/hyper/commit/6508d05e5f0ccf747d114de59867567c37320718

**Comment by ppot** [comment]
@skad0 Make a new issues plz
