### ISSUE TITLE
[Bug][Windows] Context menu is showing Hyper but trows an error when clicked.

### ISSUE THREAD

**Issue by stefanivic** [zeit/hyper#1133]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro, Version 1607, OS Build 14393.479
- **Hyper.app version**: Hyper 1.0.0
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

Steps to reproduce : 
1. Clean install Hyper 1.0.0.
2. Right click on desktop.
3. Click on Hyper.

Images off the issue : 
![](https://i.gyazo.com/0b4ff19bc68a7f4769787457f91f9f71.png)
![](https://i.gyazo.com/188e640d7dcae281b3d4e5a4fc2f5654.png)

**Comment by klauscfhq** [comment]
I am also on Windows 10 Pro - Version **1607** - OS Build **14393.479** - and the issue is not present 🤔
Maybe try running the installer as administrator, if you have not already.
Also, the right click prompt to run Hyper, is kinda different for me;
![untitled](https://cloud.githubusercontent.com/assets/12670537/21120383/b7d79ea4-c0cf-11e6-9d87-7c89e91403ed.png)
Hope that helps!

**Comment by berwyn** [comment]
Windows 10 Pro 1607 Build 14965.1001 here, and my "open here" option works correctly, but also matches klauscfhq's
![image](https://cloud.githubusercontent.com/assets/1403744/21120894/cc60d758-c086-11e6-85c8-369cc55979dc.png)

**Comment by stefanivic** [comment]
Yeah, looks like something happened during the first install. I tried again as administrator but the issue was still there. Had to remove hyper from the context menu first and reinstall as administrator.  

@CodeTheory you can close the issue.

**Comment by bayesrule** [comment]
same bug here, Win 7.
Wondering how to remove hyper from the context menu.... @stefanivic @CodeTheory

**Comment by lednhatkhanh** [comment]
Same bug here, trying to remove it and rerun with administrator.

**Comment by bayesrule** [comment]
Also, tried to uninstall Hyper from Win 7. The uninstallation is not clean at all...

**Comment by lednhatkhanh** [comment]
@CodeTheory I think this bug should be reopen, I tried to remove hyper, restart windows and reinstall with administrator but still doesn't work, I'm on windows 10.

I also have the exact same issue with GitKraken, but VScode works fine.

Also, all my 3 computers have the same problem, I think it's a problem with Electron itself or something, because I just recently reinstall windows on both 3 computers, and I didn't facing this error before the  reinstallation.

**Comment by lednhatkhanh** [comment]
@bayesrule After removing Hyper, go can go here `HKEY_CLASSES_ROOT\Directory\Background\shell` (search for `regedit` in windows search) and delete the `Hyper` folder there.

**Comment by stefanivic** [comment]
@lednhatkhanh yeah that is exacly how i removed it, but after a fresh install as administrator it worked fine.

**Comment by Speiser** [comment]
A fix for it is:  go to `HKEY_CLASSES_ROOT\Directory\Background\shell\hyper\command` (in regedit).  
Change `default` value to `C:\Path\To\Your\hyper.exe %V`

**Comment by neilsustc** [comment]
> A fix for it is: go to `HKEY_CLASSES_ROOT\Directory\Background\shell\hyper\command` (in regedit).
Change `default` value to `C:\Path\To\Your\hyper.exe %V`

There is a problem that everytime when hyper updates automatically, I have to redo the fix as above.

I think it could be better to ask for administrator permission when installation (like what vscode does)
We can see a difference on the icons (I don't have a vscode installer now, but you will know what I said from the picture)
![installer](https://cloud.githubusercontent.com/assets/7588612/23820162/88970760-064d-11e7-8d29-3b204a75f780.png)
