### ISSUE TITLE
Solid black border below tab when background color is non-black

### ISSUE THREAD

**Issue by Tyriar** [zeit/hyper#114]
Ubuntu 16.04

![image](https://cloud.githubusercontent.com/assets/2193314/16889434/412daf64-4a9b-11e6-8a51-d4daad2d415f.png)

**Comment by kaicataldo** [comment]
Also seeing this - looks like the border-bottom color might be hardcoded:
<img width="345" alt="screen shot 2016-07-16 at 12 30 51 am" src="https://cloud.githubusercontent.com/assets/7041728/16892771/93fd847a-4aec-11e6-90b5-e801b15329ac.png">

**Comment by Tyriar** [comment]
Problem line: https://github.com/zeit/hyperterm/blob/master/app/lib/components/tab.js#L85

It's not just a matter of making it transparent because .tabs has it's own border and the top-left is padding not an element meaning the .active tab probably needs to pull in the background color. https://github.com/zeit/hyperterm/blob/master/app/lib/components/tabs.js#L73

**Comment by kaicataldo** [comment]
I took a look at this, and I'm having trouble passing in the `backgroundColor` from the props to the aphrodite styles object. I'm new to React/Redux, though, so there's a good chance I'm just doing it wrong.

When `css` is called, the context has changed (maybe because of the wrapper helper method?) and the tab's props are no longer available in `styles`. I'll take another look, and apologies if I'm missing something obvious!

**Comment by yyx990803** [comment]
For the time being, I hacked around this by adding some main window CSS:

``` css
.tab_active:before { border-color: $YOUR_BG_COLOR }
```
