### ISSUE TITLE
Have you considered Rewriting It In Rust?

### ISSUE THREAD

**Issue by danielreisinger** [zeit/hyper#1228]
javascript is a shit

**Comment by dotcypress** [comment]
![tumblr_oeukcetyu11rojgemo7_r1_250](https://cloud.githubusercontent.com/assets/1333916/21236767/34a0a0d8-c2b1-11e6-8453-a6fbdc220980.gif)

**Comment by stefanivic** [comment]
@danielreisinger The point of the project was to create beautiful and extensible experience for command-line interface users, built on open web standards. There are much more JS developers out there and this creates a huge potential for people to contribute to the project and develop plugins an themes for it ( as you can see here : https://github.com/bnb/awesome-hyper ). As for now no, but i am sure there is a terminal built in Rust if not you are free to write your own terminal one. :D 

@CodeTheory @ppot

**Comment by pablopunk** [comment]
@danielreisinger really, the first thing ever you do on github is a nonsense aggressive issue.

**Comment by danielreisinger** [comment]
>aggressive
kek

**Comment by CodeTheory** [comment]
Hi there. Thanks for the contribution. I can tell that you're a really busy person and don't have much time to submit meaningful issues, so I really appreciate you taking the time to submit one to us.
However; we don't agree with you when it comes down to what language Hyper should be written in. So, I'm sorry but I've closed your issue. 

I regret to close and lock this issue since it really seems like you're a genuinely nice person just trying to help a growing community who submit a lot of their time in attempt to create products that aid you in your daily work life. It really seems like you cared about this and submitted this issue in respect to that. 

Anyway; I hope you continue to enjoy using Hyper written in JavaScript.
