### ISSUE TITLE
Title bar gap on Linux/Windows is awkward when there are no tabs

### ISSUE THREAD

**Issue by Tyriar** [zeit/hyper#127]
The height of `.tabs_nav` should be zero when there are no tabs on non-OS X operating systems.

![image](https://cloud.githubusercontent.com/assets/2193314/16889686/0ac07c02-4a9d-11e6-8fe0-af8961eaebfd.png)

**Comment by WoodyWoodsta** [comment]
I think it would be great if a frameless `BrowserWindow` was used in the non-MacOS environment (since `titleBarStyle` is only supported in macOS) so that the macOS look can be achieved. I'm unsure if this is behavior that others would want, given window controls would be created by hyperterm and will most likely conflict visually with user's Linux themes.

**Comment by efegurkan** [comment]
IMHO it would be awesome if all platforms would look same. So using frameless window on other platforms would be a good idea. Also using frameless window would open theming support for the close buttons.

**Comment by matheuss** [comment]
#113 😅
