### ISSUE TITLE
Nano constant glitches

### ISSUE THREAD

**Issue by vaporwavie** [zeit/hyper#1271]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 14.04 LTS
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/vaporwavie/851fd24e33b001291ca263b935288e9d
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla
## Issue

Hello! I've been using Hyper for a few weeks, and I recently witnessed a "glitch": Nano simply doesn't work **at all**, and every single time I tried to use it, I was forced to quit hyper so I could try again, with no good returns at all. Hope it helps reporting anything :smile:

**Comment by fcgomes92** [comment]
* **OS version and name:** ArchLinux Latest
* **Hyper.app version:** 1.0.0
* **Link of a Gist with the contents of your .hyper.js:** https://gist.github.com/fcgomes92/9ae458c80ce29258f2a85576ef28a81b
* **The issue is reproducible in vanilla Hyper.app:** Is Vanilla

+1
For me all the shortcuts fail. For example: If i hit CTRL + X nothing happens.

**Comment by nbolten** [comment]
This is a dupe of #1069 and #1132. Basically, `hyper` uses <kbd>Ctrl</kbd> as its mod key by default on Windows and Linux, which is not ideal. This does not impact Mac users, as the <kbd>Cmd</key> is used there.

I've put in a pull request at #1191 and would appreciate any confirmations/feedback you can provide there.

**Comment by vaporwavie** [comment]
Okay. Thanks for replying!
