### ISSUE TITLE
oh-my-zsh issues

### ISSUE THREAD

**Issue by sebastianks** [zeit/hyper#1289]
Hi.

When I am installing oh-my-zsh it's working for the current window, but when I am closing Hyper and opening Hyper again it's not initialized. Do I have to init. it in some way? Or tell Hyper to always use oh-my-zsh?

**Comment by philippbosch** [comment]
did you change your system shell to zsh – `chsh -s /bin/zsh`?
there's also a `shell` option in the Hyper config (see https://hyper.is/#cfg)

**Comment by sebastianks** [comment]
Thank you very much! setting shell = '/bin/zsh' in ~/.hyper.js did the trick for me.

**Comment by CodeTheory** [comment]
Did you resolve your issue @sebastianks? Are we okay to close this now?

**Comment by sebastianks** [comment]
Hi @CodeTheory

Yes - Thank for your help

**Comment by nobleach** [comment]
This appears to have no effect for me. I'm running on a network/managed account, so changing my shell system-wide isn't obvious. (`chsh` doesn't work) Was the `shell` key in config deprecated?

**Comment by sinedied** [comment]
How to get rid of the `%` sign on startup when doing this?
See
![image](https://cloud.githubusercontent.com/assets/593151/26001911/35b10a48-372e-11e7-90c6-a11058362c7f.png)

**Comment by team6612** [comment]
@sinedied Same problem here

**Comment by yossepbb** [comment]
This is the Z Shell configuration function for new users,
zsh-newuser-install.
You are seeing this message because you have no zsh startup files
(the files .zshenv, .zprofile, .zshrc, .zlogin in the directory
~).  This function can help you with a few settings that should
make your use of the shell easier.

You can:

(q)  Quit and do nothing.  The function will be run again next time.

(0)  Exit, creating the file ~/.zshrc containing just a comment.
     That will prevent this function being run again.

(1)  Continue to the main menu.

(2)  Populate your ~/.zshrc with the configuration recommended
     by the system administrator and exit (you will need to edit
     the file by hand, if so desired).


Hy guys, someone can help me? my zsh keep send me this msg when i try to open a new tab.

**Comment by manohar-voggu** [comment]
> How to get rid of the `%` sign on startup when doing this?
> See
> ![image](https://cloud.githubusercontent.com/assets/593151/26001911/35b10a48-372e-11e7-90c6-a11058362c7f.png)

https://github.com/zeit/hyper/issues/2144

**Comment by arjawn** [comment]
Same problem and setting shell = '/bin/zsh' in ~/.hyper.js did the trick for me. Thank you!
