### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by leo** [zeit/hyper#1443]
Coming from Terminal.app, I'm missing this feature a lot!

<img width="589" alt="screen shot 2017-01-22 at 19 55 45" src="https://cloud.githubusercontent.com/assets/6170607/22184988/fa154fa0-e0dc-11e6-9998-9ea9a1155b8a.png">

**Comment by matheuss** [comment]
#541 🤗

**Comment by tntu** [comment]
#541 has been open for quite some time since the early version and still a feature so commonly needed is yet to come or any updates posted on the issue as to what it's delaying it.

I understand this is free software and I appreciate the hard work that has been put into it by a growing number of people and I would love to see this become the go to cross platform terminal app, but that will not happen without a key feature such as basic text search and that would be sad.

**Comment by chabou** [comment]
There is a PR: https://github.com/zeit/hyper/pull/1793
And there is a plugin too: https://www.npmjs.com/package/hyper-search
