### ISSUE TITLE
CTRL-Y doesn't work inside VIM/Linux

### ISSUE THREAD

**Issue by dmitry-saritasa** [zeit/hyper#1512]
- **OS version and name**:  Fedora 25
- **Hyper.app version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/dmitry-saritasa/9fc435adf8eecda554ab813c39c2dc0d

## Issue
When I copy text in the browser and try to insert it inside vim (inside hyper) - no paste happens (Ctrl-Y)

how to solve?

**Comment by Anzumana** [comment]
just for reference. works for me on mac.
OS version and name: 10.10.2
Hyper.app version: 1.1.0
Does someone have Fedora in order to debug this ?

**Comment by celevra** [comment]
same here:
https://github.com/zeit/hyper/issues/1069
https://github.com/zeit/hyper/issues/1132

the problem is that hyper uses ctrl+<?> keys, on osx it uses cmd+<?> so, no problems on osx. 
But on windows and linux it isn't usable when it blocks the normal shortcuts.
i hoped in 1.2.0 its getting fixed, but... no it is not.

**Comment by elchinot7** [comment]
I been used CTRL-a as prefix for tmux, however in a Hyper terminal CTRL-a selects all text. This simple issue is stopping me from use Hyper as my every-day terminal app.

**Comment by nikos9742** [comment]
True, i want to use hyper but all the ctrl + keys issues makes me sad and i have to constantly use another term :/

**Comment by Anzumana** [comment]
are you always only mapping ctrl+ singlekey or do people use ctrl + manykey mappings when changing tmux keybindings.

**Comment by ppot** [comment]
close in #1876
