### ISSUE TITLE
tmux mouse control doesnt work anymore in 1.2.1

### ISSUE THREAD

**Issue by bradparks** [zeit/hyper#1593]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac El Capitan 10.11.6 (15G1217)
- **Hyper.app version**: 1.2.1.1527
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/bradparks/9bb7093c811fb41bbec1bdc082364151

- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_:  NA

- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`. 
## Issue
I use tmux, and when using hyper.sh, I can't use the mouse to select different panes in a window. If  I bring the exact same session up in iterm2, I can use the mouse fine and clicking in a pane navigates to the pane in tmux.

**Comment by lyndsysimon** [comment]
I was able to reproduce this issue.

----

- **OS version and name**: macOS Sierra 10.12.3 (16D32)
- **Hyper.app version**: 1.2.1.1528
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [link](https://gist.github.com/lyndsysimon/f7ec05fc89cd6ab00ea4cda0c068858b) - also contains my `.tmux.conf`.
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_:  N/A
- **The issue is reproducible in vanilla Hyper.app**:  Yes

**Comment by thenets** [comment]
Mouse events don't work for me too.

Hyper 1.3.3
Windows 10 Pro
With cmd.exe, powershell.exe and bash.exe

**Comment by nesl247** [comment]
Same issue here. Hyper 1.3.3 on Win 10 Pro Creators Update.

**Comment by HowardStark** [comment]
Same issue here. Hyper 1.3.3, macOS 10.12.6, tmux 2.2

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by bradparks** [comment]
Fixed for me! Thanks!
