### ISSUE TITLE
Hyper on Windows 10 goes boom when it cannot access a JUNCTION (symbolic link)

### ISSUE THREAD

**Issue by ghuntley** [zeit/hyper#1687]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 14393.953
- **Hyper.app version**: latest (installer from website)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_:  N/A
- **The issue is reproducible in vanilla Hyper.app**:`Is Vanilla`. 

## Issue
1) Install Hyper
2) 💥 

![image](https://cloud.githubusercontent.com/assets/127353/24087275/c58f18de-0d68-11e7-9d37-a703881e2e36.png)

1) Launch Hyper
2) 💥 
![image](https://cloud.githubusercontent.com/assets/127353/24087275/c58f18de-0d68-11e7-9d37-a703881e2e36.png)

## omg why is this happening?

![image](https://cloud.githubusercontent.com/assets/127353/24087290/e20139ac-0d68-11e7-92d5-bb265411db43.png)

The problem is caused by a JUNCTION/symbolic link to a directory aka `mklink /d` which currently cannot be accessed as the volume is not mounted.

![image](https://cloud.githubusercontent.com/assets/127353/24087309/0b552782-0d69-11e7-96bd-5a89f49bfa54.png)

**Comment by ghuntley** [comment]
p.s. hyper works after deleting the junction

`fsutil reparsepoint delete work`
`rm work`

🎉

**Comment by postgrep** [comment]
Same behaviour on my machine.
An unhandled exception is thrown immediately and the program exits.

Happens immediately after running the installation bootstrapper .exe
Happens when trying to start Hyper later on from the start menu.
Happens when trying to uninstall the Package via Apps & Features

I had a junction in my ntfs home dir pointing to home dir in drvfs of wsl
I aslo had a symlink in my ntfs home dir pointing to my dropbox on another volume
The symlink did not cause any problem. but the junction did.

I guess the drvfs of wsl cannot be accessed through a junction and thus it throws
"directory name is invalid"

I deleted the junction. Now everything works fine.

OS: Windows 10 Pro, 64 bit.
Version: 1703
OS Build: 15063.138
Package: hyper-Setup-1.3.1.exe

![1d854822-25c1-11e7-86d5-fb654687965a](https://cloud.githubusercontent.com/assets/1336461/25228875/505cf2b0-25ce-11e7-9bdf-5ff062cab165.PNG)

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by thedonquixotic** [comment]
@Stanzilla I am still having problems with this issue and have logged a ticket for it here: https://github.com/zeit/hyper/issues/3132

Did anyone else find a fix?
