### ISSUE TITLE
E388 when using VIM

### ISSUE THREAD

**Issue by brograhamer** [zeit/hyper#1751]
Set my shell to updated oh-my-zsh. Editing anything in VIM using arrow keys gives me an E388 error. Updated to VIM8.0 thinking that might solve the problem, yet it persists. I'm on Windows 10. This is a pretty bare install, so I'm unsure what's wrong when VIM works well in ConEmu.

**Comment by chabou** [comment]
How do you use zsh? With WSL?
Maybe duplicate (or related to) #1514

**Comment by agrahamwd** [comment]
Precisely, love the zsh shell and am more used to it than bash. 

Tried that thread before posting here, nothing from it worked.

**Comment by chabou** [comment]
Did it work with bash? And with vanilla zsh (without any `.zshrc`)?
If it work, can you give us your `.zshrc`?

**Comment by agrahamwd** [comment]
Fixed this issue, Arrow keys would simply throw the arrow, so `vim ~/.vimrc` and adding `:set term=builtin_ansi` seemed to solve this problem. Other consoles did **not** share this problem before and after Hyper was installed, so this specifically seems like a Hyper issue.

Thoughts as to why? Is this a bug?

**Comment by MartyGentillon** [comment]
I wonder what you $TERM variable is.  It looks to me like, for some reason, vim is trying to use escape sequences that Hyper doesn't support.

**Comment by kylepaulsen** [comment]
I'm also seeing this. Other consoles work fine. My $TERM var is: xterm-256color
Also, I'm using the windows version (v1.3.1).

**Comment by droided4u** [comment]
Hi, new user here, sorry for resurrecting. I was getting same "E388: Couldn't find definition" error with android terminal emulator which is working in linux mode. @brograhamer 's fix worked for me so i signed up to thank him. Thank you very much sir! I was getting E388 when i press arrow keys. What is weird for me is that my first press was returning right arrow regardless of which one i press. Also i didn't experience any text showing up. Not that i have a clue but someone might have. I'm running debian core through linuxdeploy app for development with a bluetooth physical keyboard. I hate using both vnc and eclipse so i didn't install anything but development stuff and what i realized is that arrow keys are not working properly in terminal emulator, i know cause i experienced similar issues with midnight commander too. I didn't care much since i can teach buttons to mc(also i use bluetooth mouse so i can click) but vim was a wash out. Luckily i found the fix.
 If you ask me, this problem is definitely terminal type based but then again i'm no expert.

**Comment by richkeenan** [comment]
Is there any news on this? I tried @brograhamer suggestion but that completely locked all the keys and I couldn't even exit (commence jokes about exiting vim). It's definitely a Hyper issue as I don't get this with other terminals

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
