### ISSUE TITLE
Make location of .hyper.js and .hyper_plugins configurable

### ISSUE THREAD

**Issue by skrysmanski** [zeit/hyper#1884]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`.

## Issue
I'm a big fan of version controlling my configuration files. With the current version of Hyper, however, this is not easily possible because the location of both `.hyper.js` as well as `.hyper_plugins` is hard coded with the home directory - and with Git (or any other VCS) it's not possible to have multiple working copies in the same directory (the home directory in this case).

So it would be nice to make the config directory configurable - e.g. with an environmental variable.

## Notes
* I've seen the [hyper-sync-settings](https://www.npmjs.com/package/hyper-sync-settings) plugin but it seems to be broken currently.
* From what I can tell it would be possible to require another file from within `.hyper.js` but this would not solve the problem of relocating `hyper_plugins`.
* On Linux/macOS one could use symlinks to work around this problem but symlinks are rather hard to use on Windows.

**Comment by chabou** [comment]
It is not possible to specify location of `.hyper.js`. But we want to support XDG (discussed in #137)

You don't need to backup/version `.hyper_plugins` directory because it is a download/cache directory. If you delete it, `Hyper` reconstruct it.

I'm a big fan of version controlled configuration files too. But it is hard to change config file location for all application. When you have a new computer to configure, you have to change all applications parameters/environnement vars. I prefer to use symlinks. You can take a look to my [personal dotfiles repo](https://github.com/chabou/dotfiles) and its [installation script](https://github.com/chabou/dotfiles/blob/master/symlink-setup.sh). With this symlink way, you can have config files everywhere in your filesystem and in the meantime, a central place for your git repository.

**Comment by skrysmanski** [comment]
@chabou Thanks for mentioning #137. This is - more or less - exactly what I was looking for. So I'm closing this issue as a duplicate.
