### ISSUE TITLE
Tabs in titlebar

### ISSUE THREAD

**Issue by zsty** [zeit/hyper#1953]
[Hyper 1.3.3] 
In the mac version of hyper, tabs are in the titlebar. Seeing as on windows and linux window controls are entirely done by electron, why do we have a titlebar?

Here's an example of tabs in titlebar (ripped from the hyper website)
![Yellow hyper with inline tabs](https://hyper.is/static/hyperyellow.gif)
and a screenshot from my linux machine (with hyperyellow for consistency between images)
![hyperbad](https://user-images.githubusercontent.com/25940563/27430287-52fe9110-578b-11e7-9351-bc0ab5af015b.png)
Please ignore my hostname 😉

**Comment by CodeTheory** [comment]
Unfortunately, Windows and Linux do not act the same way with draggable areas. To preserve the functionality of the draggable window whilst still being able to click the tabs, we needed to separate them on both Windows and Linux 😢. We would have loved it to be the same but this is what we had to do to make these features functional.

**Comment by zsty** [comment]
@CodeTheory You're probably right, but it would be nice to have an option for force this and have only the current tab draggable. I'll try do this now and see how it feels, and if it works I might do a PR.

**Comment by zsty** [comment]
@CodeTheory It seems we _could_ (!!) do this with [electron-drag](https://github.com/kapetan/electron-drag). I haven't tried this yet, but it looks promising-ish.

**Comment by AnnoyingTechnology** [comment]
Cursor based actions (drag-drop) for power user/developers are not much used (because slow and imprecise), keyboard shortcut are often preferred.

On the other hand, screen real-estate is an important thing and having tabs in the titlebar seems more important than the drag-drop feature for the targeted users. Maybe you could reconsider ?

Deepin terminal made that exact choice !
![Screenshot from 2019-09-30 12-00-03](https://user-images.githubusercontent.com/5336824/65869070-e9870a00-e379-11e9-90f1-9d8361177897.png)
