### ISSUE TITLE
.hyper.js error "'module' is undefined" on Windows 10 after installation with Chocolatey

### ISSUE THREAD

**Issue by LoZeno** [zeit/hyper#1962]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro 1703
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/LoZeno/21bd7b4baa2371b6079c24852ca7131c
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
I installed Hyper using Chocolatey. Right after I launched it the first time, I tried to edit my preferences, but I get the following message:

Script: C:\User\<myUser>\.hyper.js
Line: 5
Char: 1
Error: 'module' is undefined
Code: 800A1391
Source: Microsoft JScript runtime error

**Comment by hawkins** [comment]
This is because your default settings for `.js` files are to run them with the Microsoft JScript runtime.

You can fix this by...

- opening the containing folder
- right clicking on your `.hyper.js` file
- select "Open With"
- click "choose another app"
- select a text editor like Atom, VSCode etc
- then check "Always use this to open `.js` files"
- click "OK"

**Comment by LoZeno** [comment]
Yeah, that was the issue!
I'm kind of ashamed that I didn't realise it myself!

thanks

**Comment by bardware** [comment]
Thanks for making clear the file is opend for edit.
I expected a dialog to come up.

**Comment by albinekb** [comment]
This is resolved in 2.0 and will be released soon 👍
