### ISSUE TITLE
Tabs in titlebar Mk 2 (The reckoning)

### ISSUE THREAD

**Issue by zsty** [zeit/hyper#1974]
###### Continuation of #1953

I'm probably dragging this on, but it seems that this is actually possible by using [electron-drag](https://github.com/kapetan/electron-drag). I'm putting a new issue up because I don't know how notifications work with closed issues and if anyone actually saw what I wrote.

Apart from this, we could also make the current tab draggable on windows and linux.

If this is added as a feature, I'd probably add it as a setting, though this is probably really bad UX.

**Comment by CodeTheory** [comment]
@matheuss didn't you try this?

**Comment by matheuss** [comment]
@CodeTheory I didn't, but since it doesn't work on Linux, it's not worth trying. 

For the record, we can't have tabs in the tittle bar on Windows and Linux because of this (via `kapetan/electron-drag`):
> Frameless windows can be dragged using the -webkit-app-region css property, but this disables all regular dom events and user interactions with the affected element [...]

For some reason, the above is **not true** on macOS – the element will receive regular DOM events.
