### ISSUE TITLE
Neovim's Beam cursor moves superslowly

### ISSUE THREAD

**Issue by blackxored** [zeit/hyper#2011]
If I enable the Neovim setting to change cursor type based on insert/normal mode, I've randomly noticed that using the arrow keys while on insert mode works insanely slow, and the cursor disappears even for some time.

**Comment by herrbischoff** [comment]
Same here. I have no hopes that this ever gets fixed though. Your issue is over half a year old and there's not even a reply of any kind. What can you do, it's a JavaScript-based terminal emulator after all. Performance just cannot be a priority in its development. From how it works, it can only be surmised its users are not doing more than running a couple of yarn commands and creating rather distracting plugins. Sadly, for any serious shell work, it borders on useless.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
