### ISSUE TITLE
Hyper fails to load shell (Fish)

### ISSUE THREAD

**Issue by saq1610** [zeit/hyper#2040]
- **OS version and name**:  Linux Mint 18.2 / Ubuntu 16.04.2
- **Hyper.app version**: 1.3.3 
- **Link of a [Gist](https://gist.github.com/saq1610/4b0581a9ac6d472fd5c25c1cd67a89e3) with the contents of your .hyper.js**: 

## Issue 
Changing the shell in hyper.js to Fish from the default shell Bash means that sometimes when i start Hyper it doesn't load the shell. This only happens around once every four tries and during this state only the cursor is shown with no prompt or error showing up. The shell prompt never loads. This only happens when using '/usr/bin/fish' as my shell. 

This bug only seems to happen on hyper, other terminal apps like Tilix, Konsole and gnome-terminal aren't affected and successfully load Fish every single time as a terminal is supposed to.

**Comment by MiracleBlue** [comment]
Hi there, long time hyper user, longer time fish user here.  This sure smells like a rather crabby problem, let's see if we can catch it hook, line & sinker before it all goes whale out of proportion!

*ahem* 

First thing's first, what fish version are you using here when this error occurs?

Also, when you see this error state occur after trying to load, open up the chrome devtools panel that electron comes with (you can find a toggle in the app's view menu, labelled "Toggle Developer Tools") and take a look at what is printed out under the console tab.  Any and all exceptions printed here will probably be quite important especially if this does turn out to be some deeper bug.  See if you can post a copy of those logs here.

In earlier days of Hyper I remember having quite a few "silent" shell errors when loading Fish, that wouldn't display in the main window.  I did eventually realise there was often a log file that did contain the actual error message fish was trying to give me even when hyper was saying nothing, so that could be happening here too.  Have you tried searching for it?  I'm not sure off the top of my head where or what that might be by default under Mint/Ubuntu, and unfortunately I'm not currently on a linux machine so I can't go look for where it might be, but if you can, try have a look for it.

One thing I did notice is the fact that you're specifying the shell path in your Hyper config directly.  Is it not set as your systems default shell?  I typically roll with fish as my OS default, and just leave that part of my hyper config as is, and it tends to automatically pick up whatever the default is.

If you're not currently setting fish as system default and are willing/able to give that a try, please do, and make sure to set `shell: '',` (empty string) in your `.hyper.js` config file so that hyper will start using the default.

Hopefully we can find a way to sort it out :) let me know how you go.

**Comment by silv4b** [comment]
I have same problem. Hyper shows me `execvp(3) failed.: Arquivo ou diretório inexistente` when i use only `shell: ''` or `shell: '\bin\fish'`, but, If a put `\bin\bash`, then works fine, but with bash shell. :/
