### ISSUE TITLE
Add keymaps map to documentation

### ISSUE THREAD

**Issue by grafa** [zeit/hyper#2167]
Hi there,

than you for amazing app.

After 1.4.x I was't able to type like half of characters so I had to downgrade to 1.3.3. It seems to be fixed in 1.4.3 but not I'm not able to use keymaps (new tab, close tab, ...). I noticed there is new keymap config property but there is no keymap map/table/docs nor any note default keymaps has changed.

Any chance to get one?

**Comment by chabou** [comment]
Default keymaps are here: https://github.com/zeit/hyper/tree/master/app/keymaps
And you can configure them: https://hyper.is/#keymaps

**Comment by grafa** [comment]
Exactly what I needed. Thank you.

**Comment by chabou** [comment]
We should add this reference in our documentation.
PR Welcome 👼

**Comment by tufank** [comment]
Hello,

I am using Hyper 1.4.3 on macos sierra 10.12.6 and modifying the keymaps just doesn't work for me. I've uncommented the example ('window:devtools': 'cmd+alt+o') and it just doesn't do anything. I've tried also setting it to other combinations like cmd+alt+5, cmd+5, no luck. cmd+alt+i works always. Also tried changing the defaults for other commands without success.

I was never able to modify keymaps (I was using 1.3.3 before 1.4.3).

What am I missing here?

**Comment by grafa** [comment]
@tufank once you change the config hyper.js reloads it automatically but the new keymaps works in newly opened winows.

**Comment by tufank** [comment]
Hey @grafa , thanks for the help.

For me,

New window -> doesn't work
Config reloaded -> doesn't work
Full config reload (cmd+r) -> doesn't work
Close window and reopen, or type exit in the shell -> doesn't work (macos apps usually tend to not exit completely)

Quit the application (cmd+q) and relaunch -> Works 

Perhaps because of my previous failures, I might have skipped relaunching the app this time while trying the example.  This is indeed some progress for me, thank you for the tip.

I still can't remap to combos like cmd+h or cmd+k. I wonder if there is a way or they are simply hard coded in the app. 

What I'm trying to do is simply:
	
  keymaps: {                                                                                                    
    "pane:next": "cmd+h",                                                                                       
    "pane:prev": "cmd+l",                                                                                       
    "pane:splitVertical": "cmd+j",                                                                              
    "pane:splitHorizontal": "cmd+k",                                                                            
  }

**Comment by chabou** [comment]
`cmd+h` is used to "Hide Hyper" (like all Mac App) and I think it is not a good idea to customize it

`cmd+k` is used to clear terminal (like other Terminal apps) and should be customizable.

**Comment by chabou** [comment]
@arojunior will be so great!
I think it is better add only references for now.

**Comment by pcnate** [comment]
Awesome!!! Thanks!
````
  keymaps: {
    "tab:next": "ctrl+pageup",
    "tab:prev": "ctrl+pagedown",
    "pane:next": "ctrl+tab",
    "pane:prev": "ctrl+shift+tab"
  },
````
