### ISSUE TITLE
Un-Clear installation commands 

### ISSUE THREAD

**Issue by Lavanaya** [zeit/hyper#2188]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

In Contribute section under "Install the dependencies",I found following problems:

1. Installation instruction for mac are not given (mac is a unix not linux system, hence mentioning only for linux won't solve problem). 
2. icnsutils is not compatible with mac
3. It is not clear whether to install yarn for all os or not as first it is specifically mentioned to download it for windows then a separate point asking to download yarn. Eg: **If you are running Windows, install yarn** mentioned in readme.

**Comment by h93xV2** [comment]
The install instructions could also be made more clear for linux.

For example:
  + The necessary packages supplied by `icnsutils` are provided by `libicns-utils` on Red Hat systems.
     - i.e. `dnf search icns-utils` is how you can get `icn2png`.
  + Saying that you need `rpm` seems redundant since Red Hat platforms usually come with it by default.
     - A new user working on a Debian platform might be confused by this.

**Comment by albinekb** [comment]
@Lavanaya the reason for there being no special stuff for mac is becuase mac is **awesome**. You don't need extra stuff and fiddle with external packages to get running. Just clone the repo, run `yarn`, `yarn dev` and `yarn app` in another window and you're off.

well you need Xcode but that's in the readme + almost every developer has it installed because it's needed by a lot of things 😄  

But: I completely agree, I think separating them makes more sense.
