### ISSUE TITLE
Start menu entry not created by hyper 2.0.2 installer

### ISSUE THREAD

**Issue by F21** [zeit/hyper#2246]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 64-bit Creators Update (latest updates)
- **Hyper.app version**: 2.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/F21/6b817008781add7f7f415d6c5316e08c
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
I am using the 2.0.2 Windows 64-bit installer downloaded from Github on a clean machine. All previous versions of hyper were uninstalled and the `.hyper.js` file and `.hyper_plugins` folder were deleted before installing 2.0.2. Hyper installs correctly, however, there does not appear to be an entry in the start menu, so it is not possible to launch hyper from the start menu.

**Comment by albinekb** [comment]
You should never install the canary versions directly, the correct way to do it is:

1. Install stable
1. Edit .hyper.js updateChannel to `canary`

Otherwise you'd get a stable update overwriting your canary version.

We should probably document this somewhere.

However, it might be the case that this is a real issue, that we broke the installer in 2.0 so it should still be investigated 👍

**Comment by MAPESO** [comment]
@albinekb I will investigate this problem with the Windows version to rule out any possibility.
