### ISSUE TITLE
Plz make an 32 bit version soon !!!!!!!

### ISSUE THREAD

**Issue by HyperGamer27** [zeit/hyper#2347]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**:

**Comment by CodeTheory** [comment]
Hi. Thanks for the report, but this isn't going to happen anytime soon, or at all. 

First of all, 32 bit systems are dying out, and the ability to support them is getting harder. Although it _may_ be possible, it's _definitely_ not the highest of priorities for Hyper. 

Secondly, the way you asked for this feature is just rude. Hyper is an open-source project where contributors donate their free time to make a product for as many people as possible whilst still being refreshing, new, and useable. If you want a feature, *kindly* request it or work on it yourself.

I'm closing this issue because I don't think it should be open. We've had discussions in other issues.

**Comment by HyperGamer27** [comment]
Thanks for answers

2017-10-11 17:05 GMT+03:00 Timothy <notifications@github.com>:

**Comment by nnmrts** [comment]
Hey! I'm on a 32-bit Debian machine. How can I help with this? Why exactly isn't hyper supporting 32-bit? I mean, generally, what is the problem? Does dependency only work or 64-bit or is it electron or...?

Yeah, if I would know that, I could help.

**Comment by chabou** [comment]
We need this PR in `hazel`: https://github.com/zeit/hazel/pull/18
