### ISSUE TITLE
All tabs hang up if there is inactivity for few minutes

### ISSUE THREAD

**Issue by abdulmannan-arb** [zeit/hyper#2370]
Hi,
I'm using hyper on mac and tabs hang & completely freeze after few minutes of inactivity. What should I do ?   
All settings are default & only 2 plugins are installed 
```
'hyperline',
'hypercwd'
```

        -
        Hyper 1.4.8
        Electron 1.7.8
        darwin x64 16.7.0

**Comment by albinekb** [comment]
Hello! Can you try out our `canary` release channel, we're working hard on releasing this to everyone, but it's not yet ready. Here's instructions on how to do so: https://zeit.co/blog/canary

also, `hyperline` is known to cause issues, since it spawns a lot of child processes on intervals (polling git etc), so if you could try without that one too.

If you still experience problems in 2.x (canary), without `hyperline`, we'll need to investigate further.

Thanks  🙌

**Comment by abdulmannan-arb** [comment]
Thanks for quick reply.
I just disabled hyperpower ( which i failed to mention earlier ) and for now, there is no such issue. I will test it again tomorrow and reopen it if it persists after following your advice.

Anyways, it is really cool application. I thing I miss from default terminal is the touch pad scroll not supported with nano editor ( maybe vi/vim too but not tested there ). 

Thanks

**Comment by abdulmannan-arb** [comment]
@albinekb I have disabled `hyperline` and it still freezes though the freeze interval is smaller than before but still ~5-10 sec freeze time.

**Comment by albinekb** [comment]
As I'm not familiar at all with windows, I don't have any clues to what could be the issue 😞  I need to get a VB up and try it myself to get a better understanding on what goes on, but don't have time to do that now, sorry 🙁  

Would be good to know if someone can reproduce this, otherwise it's something in your setup that's causing it, would be good to rule that out.

**Comment by abdulmannan-arb** [comment]
I'm on mac and using extra monitor.
To reproduce: 

- Open multiple applications in full screen.
- Open hyper in full screen as well & open multiple horizontal/vertical tabs 
- Switch to other application & after sometime switch to hyper. It will be frozen.

**Comment by albinekb** [comment]
woah, sorry I mixed this up 😂  I'll try it right now (if i can find my USB-C adapter 🙄 )

**Comment by abdulmannan-arb** [comment]
I face it when doing all of them at once. Haven't checked with 1-1 steps.

**Comment by WandyLau** [comment]
emm, new to this app, looks cool. But how can I start using it? any examples or tutorial?

**Comment by albinekb** [comment]
@WandyLau check out https://hyper.is, or join us at https://zeit.chat if you need help 👍  This issue is for *All tabs hang up if there is inactivity for few minutes*, not support chat 🎉

**Comment by rgstephens** [comment]
Thanks for this thread I was also running into a hang of all tabs on Mac anytime I ran emacs. Removing hyperline alone did not fix this issue however upgrading with the canary option (now on 2.0.4) resolved the issue.

However, there's now a much less serious but annoying problem when exiting emacs the prompt and all text entered is underlined.

**Comment by andig** [comment]
Sorry if I'm late to the party and if this is more obvious than I've noticed: if you're on hyper 1.4.8 you'll need to add the `canary` option to go to (currently) 2.1. I'll still need to watch if that fixes the problem.

**Comment by rgstephens** [comment]
Thanks, I'm on 2.1.1 (canary) and still have the underline issue after exiting Emacs.  Here's a screen shot.

<img width="532" alt="screen shot 2017-11-28 at 9 39 15 am" src="https://user-images.githubusercontent.com/846052/33334839-283b08f2-d420-11e7-90ce-4df175d2f124.png">
