### ISSUE TITLE
Settings Issue - Does not update terminal

### ISSUE THREAD

**Issue by defcasts** [zeit/hyper#2414]
When I edit any settings like font size for instance and reload the terminal it has absolutely no affect on the terminal.

**Comment by Cameron-Grams** [comment]
I upgraded to 2.1.1 and the settings for the cursor type are not responding in addition to font size.  The .hyper.js file is able to select a flashing cursor, but the cursor type (BEAM instead of BLOCK) did not respond to the settings.  Based on defcasts' comments it seems that some settings changes are working, others are not.

**Comment by chabou** [comment]
@Cameron-Grams See #https://github.com/zeit/hyper/issues/2248 (will be fixed by https://github.com/zeit/hyper/pull/2437)
