### ISSUE TITLE
Zoom In Zoom Out KeyMaps not working

### ISSUE THREAD

**Issue by EdgarACarneiro** [zeit/hyper#2448]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Microsof Windows Home 1703
- **Hyper.app version**: 2.1.1 (canary), commit: c62e042
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`.

## Issue
Zoom in and Zoom out key maps (CTRL + PLUS, CTRL + MINUS, respectivelly) not working. This key maps were working in previous releases, so I assum they are expected to work.

**Comment by campbelldgunn** [comment]
- [X] I am on the latest Hyper.app version
 - [X] I have searched the issues of this repo and believe that this is not a duplicate
* **OS version and name:** Ubuntu 17.10 (artful)
* **Hyper.app version:** 2.1.1 (canary), commit: [be4b2c8](https://github.com/zeit/hyper/commit/be4b2c8870f12704cfb13681eac663fe3c7822d3)
* **The issue is reproducible in vanilla Hyper.app:** `Is Vanilla`.

## Issue

Zoom in and Zoom out key maps (CTRL + PLUS, CTRL + MINUS, respectivelly) not working. This key maps were working in previous releases, so I assum they are expected to work.
