### ISSUE TITLE
Performance regression with maximized window on 2.0.0-canary.9

### ISSUE THREAD

**Issue by chabou** [zeit/hyper#2592]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra (10.12.6 (16G29))
- **Hyper.app version**: 2.0.0-canary.9

## Issue
We have a huge perf regression with `xterm3` with a big/maximized window (using `vi` for example)

xterm2 (2.0.0-canary.8)
![hyper-xterm2-vi](https://user-images.githubusercontent.com/4137761/34846499-a9f7f560-f718-11e7-898b-576d6a7e8378.gif)

xterm3 (2.0.0-canary.9)
![hyper-xterm3-vi](https://user-images.githubusercontent.com/4137761/34846513-af9c453e-f718-11e7-88d8-80cc9b7e4fe8.gif)

Performance recording with xterm3
![capture d ecran 2018-01-11 a 21 41 45](https://user-images.githubusercontent.com/4137761/34846545-c3ffd5e0-f718-11e7-9d10-fed304f28c76.png)

Try with last 1.8.2-beta.3 Electron version and no change.

I have same performance issue with VSCode

cc @Tyriar

**Comment by Tyriar** [comment]
I'm guessing this is what @rauchg was seeing. I suspect this branch will fix the issue https://github.com/Tyriar/xterm.js/tree/1063_minimize_drawing by no longer redrawing everything but only the first 4 columns.

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/1063

**Comment by Tyriar** [comment]
@chabou also how big is your windows cols/rows exactly when you're seeing these 500ms frames?

**Comment by Tyriar** [comment]
@chabou did you see this in older builds using the canvas renderer?

**Comment by ppot** [comment]
Looking at this it look like it's close to be fullscreen?

**Comment by bgw** [comment]
I'm running into this issue too. It's especially bad on my 1440p screen, to the point where I can't use hyper, since every keystroke in vim causes a 300ms (or more) frame.

I tend to have around 320 columns and maybe 90 rows or so.

**Comment by bgw** [comment]
[Here's my vimrc](https://github.com/bgw/dotfiles/blob/master/vimrc). It's not easy for anyone to pick up and use though, because it depends on a large set of plugins installed using git submodules.

It turns out that I was setting the background color with vim (though I was just setting it to the same color as my terminal's background, and I'm not using 256 colors). Running `:hi Normal` gives:

```
Normal         xxx ctermfg=7 ctermbg=0 guifg=#d8d8d8 guibg=#181818
```

and running `hi Normal ctermbg=none` improves performance significantly.

A took a look at how alacritty does this, and [it looks like they populate a glyph cache/atlas when drawing characters](https://github.com/jwilm/alacritty/blob/master/src/renderer/mod.rs), so that the cache is filled with character color combinations that are actually in use, whereas xterm.js is just using a static cache. I'd be interested in trying to implement a similar approach (maybe a simple LRU cache) in xterm.js.

**Comment by passcod** [comment]
Unsure if this is related, but I have a 4k screen, Hyper maximised, and experiencing **>1s** pauses. Worse in vim, going up sometimes to ~10s pauses.

**Comment by Tyriar** [comment]
@bgw yeah we only cache with the standard background, and then turn the bg transparent to retain SPAA and make it look decent with overlapping chars.

A dynamic cache is something I've been thinking about for a while, it would definitely be cool but it would be a fair bit of effort to implement.

**Comment by chabou** [comment]
I'm using https://github.com/yosiat/oceanic-next-vim Color theme.

Testing with a 320colx90rows term : frame render time is 500ms in vim.
I can confirm that setting `ctermbg=none` on Normal preset reduces frame render time to 80ms.
Disabling this theme (it uses some other `ctermbg`) reduces it to 50ms.

Very nice catch @bgw 👍

**Comment by Tyriar** [comment]
There are also huge gains that could be made if the user doesn't care about subpixel AA as then the background color doesn't need to be cached as well.

**Comment by rauchg** [comment]
I can also confirm that disabling the theme made it mindbogglingly fast 🤣

**Comment by rauchg** [comment]
Great detective work @bgw !

**Comment by Tyriar** [comment]
On second thought we would still need to check the background, but it would be based on the luminance of the color, not the exact color. And some backgrounds should be able to share without it looking weird.

**Comment by portenez** [comment]
+1 on this issue, I encountered it this morning as well. canary9 caused this, but not canary 8.

**Comment by portenez** [comment]
Disabling the theme made it fax again. I was using oceanic next theme as well.  I'm using nvim, and couldn't quite  apply @bgw's fix. I guess I just don't know how to apply it.

**Comment by hew** [comment]
I found that disabling 
  * colorscheme 
  * `set termguicolors`

Gives me the best workaround performance on Neovim.

**Comment by bgw** [comment]
FYI, I'm working on an implementation of a dynamic character atlas for xterm.js that allows characters with different background colors to be cached, which should fix most people's performance issues. It generates a character atlas that looks something like:

![selection_031](https://user-images.githubusercontent.com/180404/36469286-90f040ca-169b-11e8-8302-935d22e79c50.png)

The current implementation [is here](https://github.com/bgw/xterm.js/commit/2f3f39380b5f4100cf6d97780b6ba8065f90372c), but it's still pretty buggy, and needs a bit of work and cleanup before I'm comfortable making a PR out of it, but things are coming along!

cc @Tyriar

**Comment by Tyriar** [comment]
@bgw nice! I had a quick look at your branch, this was the main bit I'm worried about:

```
"lib": ["DOM", "ES6", "DOM.Iterable", "ScriptHost"]
```

I think using these feature would break some browser support like IE11.

**Comment by Tyriar** [comment]
@bgw I created https://github.com/xtermjs/xterm.js/issues/1294 to track this, the issue I pointed to before https://github.com/xtermjs/xterm.js/issues/1063 is a different set of optimizations that can be tackled separately.

**Comment by albinekb** [comment]
Why do you need IE 11 support @Tyriar Isn't performance more important than compatibility for xterm? 😄

**Comment by Tyriar** [comment]
@albinekb well it's more about developer convenience than performance, but IE11 support is needed to run xterm.js within Visual Studio 🙂 https://github.com/Microsoft/WhackWhackTerminal

**Comment by Tyriar** [comment]
@bgw also are these different characters? Looks like 3 space chars?

<img width="86" alt="screen shot 2018-02-21 at 8 21 27 am" src="https://user-images.githubusercontent.com/2193314/36491716-49fc8242-16e0-11e8-8f95-3bcf35ac4475.png">

I notice 3 dark grey ones too?

**Comment by bgw** [comment]
@Tyriar I need an ordered map implementation for the LRU cache, so I'm relying on the ES6 Map implementation, which guarantees insertion order iteration. We'll either need to pull in a polyfill, or I'll need to write a minimal ordered map implementation myself. Alternatively, we can try relying on the iteration order of objects in JS, but that's also a fairly new addition to the spec, though every major browser does implement it.

Regarding the space characters: I use powerline, and that screenshot is from the demo page which doesn't use the right font, so I'm guessing it's just a couple of characters that didn't render quite right.

The diff isn't ready for review yet, I just wanted to let people know that I'm working on it, so that nobody else starts to work on the same thing.

**Comment by Tyriar** [comment]
@bgw 

> We'll either need to pull in a polyfill, or I'll need to write a minimal ordered map implementation myself.

Probably a polyfill is the way to go, we can tackle that later though.

> Regarding the space characters: I use powerline, and that screenshot is from the demo page which doesn't use the right font, so I'm guessing it's just a couple of characters that didn't render quite right.

Makes sense.

---

Something else you might notice with the current implementation is that the default background color is pulled off of characters in the character atlas, this is so characters that are overlaid on wide glyphs will not completely override them. An example:

<img width="203" alt="screen shot 2018-02-21 at 9 46 05 am" src="https://user-images.githubusercontent.com/2193314/36496096-1b49523e-16ec-11e8-8eee-db10f028ced6.png">

We may just want to draw uncached for character that are on top of wide chars to avoid the bad antialiasing. As you can see wide characters are also something else to consider, let's try target just plan single width characters with this change initially before trying to cache wide ones 😄

**Comment by bgw** [comment]
FYI: Even with the dynamic char atlas patch set, drawing characters with a background is slower than without, since we make a new call to `fillRect` for each character (even when adjacent characters are the same color), which ends up being expensive (it takes up nearly half the render time for me).

I'm hoping to tackle that problem next, but you might still want to stick with the `:hi Normal ctermbg=none` hack for now.

**Comment by chabou** [comment]
@bgw Thank you so much for your hard work. This is totally amazing. Be sure, that we'll give you our feedback.

**Comment by bgw** [comment]
FYI, xtermjs/xterm.js#1413 should negate the need for the `:hi Normal ctermbg=none` hack once it lands (and hyper cuts a release including it), since it makes the background drawing operation an order of magnitude faster.
