### ISSUE TITLE
How to use PowerShell with Hyper?

### ISSUE THREAD

**Issue by stephane-archer** [zeit/hyper#2645]

**Comment by aaronr0207** [comment]
Update your .hyper.js file and change the "shell" variable to point your desired shell

`shell: 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0',`

**Comment by brandon93s** [comment]
You'll probably want to remove `--login` from `shellArgs` as well. Example PowerShell config: https://gist.github.com/brandon93s/fcd4c2f00d16f140169344da3ba3ae15

**Comment by stephane-archer** [comment]
Thank you guys!! 👍

**Comment by tiagoanleite** [comment]
FYI, for those running 64-bit Windows (it's 2018 and you should!) you just have to replace the `System32` to `SysWOW64` from @aaronr0207 comment

`C:\\Windows\\SysWOW64\\WindowsPowerShell\\v1.0\\powershell.exe`

**Comment by antonmata** [comment]
Regarding using the `SysWOW64` version. Contrary to how it is named, it is actually the **32-bit** version. You should use `System32` if you want to use the **64-bit** version.

You can verify this by querying for the size of `intptr`:
```
PS C:\> [intptr]::Size
```
This returns the size, in bytes
* If using `SysWOW64`, the result is `4`, which means it is **32-bit**
* If using `System32`, the result is `8`, which means it is **64-bit**

This makes sense because [WoW64](https://en.wikipedia.org/wiki/WoW64) is just a subsystem to emulate a 32-bit environment. Probably Microsoft just did not bother renaming `System32` since a lot of systems have that as a dependency.

Source: [How to Tell if PowerShell is 32-bit or 64-bit](https://www.gregorystrike.com/2011/01/27/how-to-tell-if-powershell-is-32-bit-or-64-bit/)
> The script in the article is quite old and might not work due to breaking changes in PowerShell, so you need to replace `[System.Runtime.InterOpServices.Marshal]::SizeOf([System.IntPtr])` with `[intptr]::Size`)

**Comment by RBalconi** [comment]
You are giving me this error, how can I solve it?

![image](https://user-images.githubusercontent.com/18688446/83903283-d78d1080-a72b-11ea-8ad0-81b161e2ccb4.png)

**Comment by techiedesu** [comment]
@RBalconi try this: https://github.com/vercel/hyper/issues/1020#issuecomment-266216491
