### ISSUE TITLE
Encoding UTF-8 Python stdout

### ISSUE THREAD

**Issue by alexedwardh** [zeit/hyper#2675]
**OS version and name**: Windows 10
**Hyper.app version**: 1.4.8 stable

## Issue

`'charmap' codec can't encode character '\u015f' in position 311: character maps to <undefined>`

Seem to experience this despite having encoding set and environment variable set. Don't experience this on default cmd.

**Comment by barkdoll** [comment]
Did you also set env variable for I/O encoding? 
`export PYTHONIOENCODING=utf-8`

I used to get the same error in other terminals, and setting this variable was the fix.

**Comment by FirstWorldSlardar** [comment]
*OS version and name*: ubuntu 16
*Hyper.app version*: 2.1

I have a similar problem. *export PYTHONIOENCODING=utf-8* or not I have the error: 
**export PYTHONIOENCODING=utf-8**

**Comment by ErickTucto** [comment]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 18.04.1 LTS
- **Hyper.app version**: 2.0.0 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Vanilla Hyper
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla Hyper
- **My shell**: [Xonsh](https://xon.sh)

![seleccion_021](https://user-images.githubusercontent.com/22831024/46508501-67fea980-c803-11e8-94cd-dfaf3db4dc1c.png)

**My `.xonshrc`**
```python
xontrib load add_variable

$PROMPT = '{env_name:{} }{BOLD_YELLOW}{cwd_base}{branch_color}{curr_branch: [{}]} {#f43}{NO_COLOR}🔥 '
$BOTTOM_TOOLBAR = '{BOLD_#66CCCC}{user}{NO_COLOR} on {BOLD_#D6A6FF}{cwd}'
$RIGHT_PROMPT = '{BOLD_#A0FF4C}{timeNow}'
$TITLE = '{hostname}'
$MULTILINE_PROMPT = '`*·.·*'

$PATH.append('/opt/blender-2.79b')
$PATH.append('/opt/android-studio/bin')
$PATH.append('/opt/SoundWireServer')
$PATH.append('/opt/node8/bin')
$PATH.append('/home/erick/.config/composer/vendor/bin')
$PATH.append('/opt/Keep')
```

**Comment by ErickTucto** [comment]
I solve it. Add this in my environment variables of my `.hyper.js`

```javascript
module.exports = {
  config: {
// ....
env: {
      LANG: 'es_PE.UTF-8' // Or en_US.UTF-8 ... etc
    },
// ...
}
```
