### ISSUE TITLE
Windows collapse, minimize and close buttons are visible on Ubuntu

### ISSUE THREAD

**Issue by jericopingul** [zeit/hyper#2691]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04
- **Hyper.app version**: Hyper 2.0.0-canary.11 (stable)
- **The issue is reproducible in vanilla Hyper.app**: Straight out of the box

## Issue
The collapse, minimize and close buttons on the top right corner are visible on Ubuntu. They should only be visible for windows. These buttons are already visible on the top left task bar.
![image](https://user-images.githubusercontent.com/11609982/36486309-1fe03c8e-1716-11e8-955b-4d30e13cb15c.png)

**Comment by albinekb** [comment]
Hmm, is this the case on all linux dists and all window managers? Or would it need to be configured per-windowmanager? 🤔 Maybe there's some way to find out if the current WM has built in window controls?

**Comment by stefanivic** [comment]
@jericopingul @albinekb this is dependent on the actual Desktop Environment. Ubuntu and Unity utilize the global menu that include collapse, minimize and close buttons but some do not have this feature available and use regular window buttons. In order to disable this you can set `showWindowControls: false,` in the Hyper config file. There is a lot of "fragmentation" in the Linux community and taking into account all the possible options is valid, but time consuming. Any PR's are welcome.

**Comment by jericopingul** [comment]
@stefanivic agreed it would be time consuming to consider all possible options. Thanks for the response.

**Comment by chabou** [comment]
Ok let's add this option

**Comment by chabou** [comment]
Ok I misunderstood. This option is already here and I am agreed with @stefanivic: Best solution is to use it depending on your window manager
