### ISSUE TITLE
Error opening preferences 

### ISSUE THREAD

**Issue by LeviathanTheGreat** [zeit/hyper#2726]
error after trying to open up preferences

Windows Script Host
Script:	C:\Users\chris\.hyper.js
Line:	5
Char:	1
Error:	'module' is undefined
Code:	800A1391
Source: 	Microsoft JScript runtime 
        Hyper 1.4.8
        Electron 1.7.8
        win32 x64 10.0.16299

**Comment by chabou** [comment]
Fixed in canary

**Comment by LeviathanTheGreat** [comment]
I found out it actually was a error to do with the default program that is set to run ".js" files, by default it is set to windows script host, which Is, as I learned, a big "no-no" as Microsoft implements its own dialect of JavaScript. 

This is one of my fist times posting on this website so i'm not sure if I'm suppose to close this issue or if I'm even suppose to be responding to this.

**Comment by chabou** [comment]
Yes you're right. Windows try to execute this JS file but this is a module that it can't understand.

In our upcoming v2 (currently released as canary: https://zeit.co/blog/canary) this is handled and if no application is set to handle JS file, it opens Notepad.

So yes, you can close this issue, because already fixed in canary update channel. And you are always welcomed to respond to any comment ;)

Thank you for your feedback 🙏
