### ISSUE TITLE
Windows Script Host Error

### ISSUE THREAD

**Issue by anderskitson** [zeit/hyper#2796]
When I got to the menu, preferences section I get a Error 'some random text' is undefined. Code 800A1391. I have included a screenshot of the error here

![image 2018-03-30 at 3 29 07 pm](https://user-images.githubusercontent.com/27952/38154481-70b733a2-342f-11e8-99a7-d61b8732fc8b.png)
 https://cl.ly/2E1s2I0m2i0G

        -
        Hyper 1.4.8
        Electron 1.7.8
        win32 x64 10.0.16299

**Comment by brandon93s** [comment]
This has been fixed in #2631 and should be available in the [Canary](https://zeit.co/blog/canary#hyper) release. 

In the meantime, you can manually edit `~/.hyper.js` with your favorite text editor or ensure that `.js` files have a proper default app assigned to them:

![image](https://user-images.githubusercontent.com/4730164/38154692-75582b52-3441-11e8-84c3-866e383f91f8.png)

**Comment by anderskitson** [comment]
Awesome, worked great thanks.
