### ISSUE TITLE
Feature suggestion: New Tab button on tab bar.

### ISSUE THREAD

**Issue by legowerewolf** [zeit/hyper#2816]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Home, v1709
- **Hyper.app version**: 1.4.8 Stable
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
What would be really useful would be to add a new tab button. I constantly forget that Hyper even has a tab system because the "new tab" button is hidden away in the hamburger menu.

**Comment by chabou** [comment]
@legowerewolf Perfect plugin idea

**Comment by christroutner** [comment]
Rather than opening another issue ticket, I have a slightly different suggestion: Give the taps the ability to be repositioned. 

I'll frequently have multiple tabs for a the same server. I like to keep the tabs for the same server close together. This would be easier if I could click-hold on a tab and move it, to change the ordering of the tabs. This same behavior is implemented in Chrome.

**Comment by XaeroDegreaz** [comment]
I would suggest having the ability to always have a tab bar visible, and like a `+` button to the right of all the open tabs to open a new tab.
