### ISSUE TITLE
Cannot Install Plugins/Themes with CLI

### ISSUE THREAD

**Issue by jajaperson** [zeit/hyper#2863]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.6
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [.hyper.js](https://gist.github.com/jajaperson/ce20efc77db81e0f8f31f04608e40845)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes, this is an issue with the CLI.

## Issue
Whenever I try to install anything with `$ hyper install` I get the following error:
```
unable to verify the first certificate
Plugin check failed. Check your internet connection or retry later.
```
I am using a school computer behind a firewall, and in the past, I have had the same problems with `npm` and `apm`. With those two cases, I was able to fix the issue by running `[cmd] config set strict-ssl false`, but there is no way of doing this with `hyper`.

I created this same issue in `hpm`, back when that was relevant, but never got a response.

> ### Update
> I now use `NODE_EXTRA_CA_CERTS` (yay), but Hyper doesn't honour this, as @jerquiaga points out.

**Comment by albinekb** [comment]
We're using a rebuilt version of `yarn` to install plugins.

I don't think there's enough demand for such a setting that it would be worth adding and maintaining.


There is a workaround:

1. Add plugin to `~/.hyper.js`
1. Open terminal and `cd ~/.hyper_plugins/`
1. Install via your low security npm `nam installl`
1. Plugins should work

Rinse and repeat for updates 👍

**Comment by timothyis** [comment]
I'm not sure there's anything we can do to help in case of your school intercepting traffic 🤔 
Feel free to re-open or comment if I'm wrong

**Comment by chabou** [comment]
Have you a specific `.npmrc`?

**Comment by chadian** [comment]
I'm getting this error even when I'm tethered to my phone's hotspot. I'm guessing that it's not related to the firewall, any recommendations for me to troubleshoot? I didn't see any errors in the network tab or console of the developer tools. Cheers!

**Comment by albinekb** [comment]
I don't think we should do that, it opens up for nasty vulnerabilities, there are better workarounds like VPN.

**Comment by hypnomaki** [comment]
Sure disabling is not a good idea. Introducing the functionality to add a custom CA would be the preferred way.
However, how does a VPN solves the problem?
I assume most people using hyper are devs or other IT guys working in a Company with a certain policy which are most likely neither allowed to build a vpn outside the company network, nor wiling to do such an affort for a "plugin"

**Comment by linonetwo** [comment]
VPN is widely used in China, we use it in the company to bypass GFW. Or we just can't open GitHub. You can build one your self.

**Comment by sskoopa** [comment]
Why wouldn't you just honor `strict-ssl=false` in the `.npmrc`?

**Comment by albinekb** [comment]
That's a huge security risk @sskoopa, it's super easy to man in the middle without correct SSL and your computer can easily get infected with malicious code.

**Comment by corbob** [comment]
I've been doing some work with getting git to work with OpenSSL instead of SChannel and recognizing. 

In that case, there is a cert bundle that it uses to determine what's valid for signing. I cannot find one for Hyper. Can anyone point me to where Hyper is looking for certificates so that I can look at the possibility of injecting our CA into the cert bundle?

I have found that around line 65135 of https://github.com/zeit/hyper/blob/canary/bin/yarn-standalone.js it talks about the ca file, but I can't for the life of me figure out where it's getting it from, or how to specify my own file.

**Comment by dannyyy** [comment]
I share the same problem than the others have. I'm behind a corporate web-proxy. Well SSL interception is also in place but the corporate root CAs where in the certificate store.

I have npm installed and set the necessary http_proxy/https_proxy/no_proxy config entries. As well as added the same entries to the environment variables and my windows default proxy settings are also set. npm, git and many others are performing very well with this settings. Only hyper is fully ignoring all kind of proxy settings. @albinekb respecting system proxy settings isn't a security flaw, requesting to download and place suspicous things in the `~/.hyper_plugins/`.

After reading this and other issues I believe hyper is not targeting serious IT professionals. I guess they promote a fancy terminal app to scriptkiddis. I see no other reason for that kind of ignorance over month/years. In addition I have to assume, that their cloud products also targets hobbyist an not serious professional customers.

For all the others `cmder` on Windows is a great terminal alternative.

**Comment by jerquiaga** [comment]
While I disagree with the tone of @dannyyy's comment, I understand the point they are trying to make.

@albinekb I agree that strict-ssl=false is a security risk. At the same time, advocating that users try to bypass their school/corporate firewall is a non-starter for most. There should be a way (preferences setting?) to set a cafile path that the yarn-standalone will use as a trusted ca so that users can CHOOSE to trust their corporate proxy ca. That way you can still maintain SSL, install plugins, and not lose your job/get expelled. This approach works very well (it's how I use npm at work currently).

**Comment by dannyyy** [comment]
@jerquiaga 
I'm sorry for my tone, but the issue doesn't start at choosing other trusted CAs. From my perspective it starts by configuring a web proxy at all!

**Comment by corbob** [comment]
One thing that should be noted is that Hyper itself has no problem checking for and installing updates to the main application behind a corporate SSL decrypting firewall. It's just the installation of plugins that fails spectacularly.

**Comment by hughes** [comment]
If I'm behind an institutional firewall that is reading my passwords and I've already installed the trusted CA, hyper is not going to protect me by refusing to install plugins. I'd have given up control of security well before getting to this point. I'm not sure what real harm this is trying to protect me from.

**Comment by zicklag** [comment]
I'm having the same issue. I am behind an HTTP proxy requiring authentication and a custom CA. NPM and yarn work absolutely fine with the proper environment variables set.

What if there was just a way to configure Hyper to use the natively installed npm or yarn to install plugins. That way, if I need to, I can tell it to use `npm` or `yarn` from the system, instead of its builtin one. The system-installed `npm` and `yarn` are already working so if Hyper just executes either one of those to install the plugins, it should be fine, right?

**Comment by zicklag** [comment]
I just realized that you can use the `localPlugins` config to get around this problem:

```js
  // in development, you can create a directory under
  // `~/.hyper_plugins/local/` and include it here
  // to load it and avoid it being `npm install`ed
  localPlugins: [
    'hyper-material-theme',
    'hyper-tabs-enhanced'
  ],
```

Just clone the plugins to `~/.hyper_plugins/local/` and run `npm install` inside of each plugin. This is the best workaround I've found so far and it isn't that much of an inconvenience for me. Might still be nice to have a more built-in config setup, but not a big deal with this workaround.

**Comment by Stanzilla** [comment]
sadly not much we can do here, we also have a ton of other issues about the CLI so closing this one

**Comment by marmelin** [comment]
Hey Folks, 
if it helps ... Hyper uses npm to update/build plugins. So set the proxy configuration for npm helped me to update plugins ... it took a while to work ... maybe because of build process . 

```
npm config set https-proxy http://myproxy:3128
npm config set proxy http://myproxy:3128
```

to get your proxy (on windows) try 
`netsh winhttp show proxy`

**Comment by Battlord8** [comment]
When i tried to install plugins, using : `hyper i <plugin>`, it showed : 'zsh: hyper is not a command', can someone please help?

**Comment by coleman-rik** [comment]
Sad, Hyper was so promising. :/
