### ISSUE TITLE
Broken text after system hibernation

### ISSUE THREAD

**Issue by mojoaxel** [zeit/hyper#2876]
I have a problem after returning from hibernation of my Ubuntu linux system:
After I "wake up" from hibernation Hyper seems to have crashed or something. :confused: 
It is still responsive but the text output is broken. Same thing for multible tabs. See below:

![peek 2018-04-19 10-37](https://user-images.githubusercontent.com/600565/38980691-ccd866ea-43bd-11e8-987b-5d75e95f294a.gif)

It looks to me like a problem with electron on linux but I don't have this problem with any other electron app.

* **system**: Ubuntu 16.04 LTS 64bit
* **hyper**: Hyper 2.0.0-canary.18 (canary)

**Comment by albinekb** [comment]
Seems like the Character Atlas map (in GPU memory) is gone and it didn't regenerate, I don't know why macOS and Windows does not have these issues 🤔 Do you have multiple GPUs?

**Comment by mojoaxel** [comment]
> Do you have multiple GPUs?

Not that I know of. I have a GeForce GTX 760/PCIe/SSE2 
But I use multiple displays.

**Comment by albinekb** [comment]
Ok, could you try using VS Code and the built in terminal, hibernate and see if you get the same issue? https://code.visualstudio.com/

We're using the same library (xterm) that has an in memory pre-baked map of all characters, if the issue is also in VS Code, we know it's an issue with xterm and we need to investigate how to detect that the map is gone from memory and re-generate, if not, we have done something in hyper that makes this happen.

Thanks and sorry for the inconvenience.

**Comment by mojoaxel** [comment]
> Ok, could you try using VS Code and the built in terminal, hibernate and see if you get the same issue? 

I could not reproduce this problem with Visual Studio Code. After a hibernation cycle the integrated terminal is still open and working.

> Thanks and sorry for the inconvenience.

Not a problem at all! Please let me know If I can help in any way.

**Comment by mojoaxel** [comment]
I can not reproduce this issue on another System also with Ubuntu 16.04 LTS 64bit and multible screens. 
I suspect it has something to do with the specific graphics-card driver!?
_Please consider this issue a low priority and feel free to close it at any time._

**Comment by szmarczak** [comment]
BTW, zooming in and out fixes the issue (possibly a workaround?)...

![peek 2018-05-07 15-38](https://user-images.githubusercontent.com/36894700/39704813-d8b2f19e-520c-11e8-941d-19f570c35585.gif)

**Comment by szmarczak** [comment]
It seems like it's a color issue. Current color (in my case `#fff`) becomes black. Changing it for example to `white` or any other fixes it.

![peek 2018-05-07 15-44](https://user-images.githubusercontent.com/36894700/39705105-b84c3b44-520d-11e8-8754-92cc82a98624.gif)

**Comment by szmarczak** [comment]
I don't think it's caused by xterm. Check out [`Atom`](https://atom.io/) and install [`minimap`](https://atom.io/packages/minimap) package. Hibernate, wake up and tada:

![peek 2018-05-08 16-25](https://user-images.githubusercontent.com/36894700/39763058-70c286d2-52dc-11e8-9ebe-2d6dca6eec96.gif)

**Comment by albinekb** [comment]
Zooming in & out confirms that the issue is with xterm CharAtlas, it's a big spritemap in-memory with the most common combinations of characters and colors, to speed up rendering in the canvas.

It must be that after hibernation in linux with some combinations loses/corrupts this memory? I have no idea how to fix it though, but one workaround would be to re-generate the CharAtlas after sleep? 🤔

**Comment by szmarczak** [comment]
> It must be that after hibernation in linux with some combinations loses/corrupts this memory?

Ubuntu is good at losing memory, that's true.

> one workaround would be to re-generate the CharAtlas after sleep

That seems to be pretty good solution. It'd amazing if this could possibly come as a experimental feature.

**Comment by szmarczak** [comment]
> Ubuntu is good at losing memory, that's true.

Here's a proof:

![peek 2018-05-08 20-16](https://user-images.githubusercontent.com/36894700/39774976-c4f1c892-52fc-11e8-811a-1858979b8484.gif)

**Comment by albinekb** [comment]
>That seems to be pretty good solution. It'd amazing if this could possibly come as a experimental feature.

I think we could do it as a plugin? And this close this issue with that since this is pretty rare and the plugin would solve it, thoughts?

**Comment by meotimdihia** [comment]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate



- **OS version and name**: ubuntu 16.04
- **Hyper.app version**: Hyper 2.0.0 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/meotimdihia/572616303a9f3eaff01b8849eec7b9d5
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
when i suspend ubuntu and start computer again, hyper screen is crash:

![selection_001_09 50 16_16_05_2018](https://user-images.githubusercontent.com/300961/40094100-36f10b40-58ef-11e8-830f-4653cdc3f302.png)

The problem just happen when i use NDIVIA binary driver:

![selection_001_09 51 27_16_05_2018](https://user-images.githubusercontent.com/300961/40094101-37208e6a-58ef-11e8-921e-3795aade7423.png)

All other programs have no problem but hyper.
I think the problem relate with Electron but i don't see the problem on Visual Studio Code.

**Comment by mojoaxel** [comment]
I now also see this in vscode:
![image](https://user-images.githubusercontent.com/600565/44773868-ebc4d680-ab71-11e8-84f3-9c53b4d8e5cf.png)
_(Image: vscode in the background, hyper in the foreground)_

**Comment by mojoaxel** [comment]
I just saw the same problem on a canvas element in Chrome. Looks like this is a problem in chromium and therefore electron!?

**Comment by albinekb** [comment]
I think it's an issue with your graphics drivers/OS @mojoaxel, doesn't happen on every distro and not on macOS nor Windows.

**Comment by mojoaxel** [comment]
This is obviously not an hyper issue. I'll close this here.

**Comment by mojoaxel** [comment]
It [might help](https://www.tonymacx86.com/threads/fix-chrome-graphics-issues-but-without-turning-off-graphics-acceleration.221328/) to run your electron app with deactivated GPU support: `--disable-gpu`

**Comment by albinekb** [comment]
Yes but that will probably give horrible performance for canvas? @mojoaxel have you found any issue about this in electron we can link to?

**Comment by albinekb** [comment]
Also I think it's possible to work around this if we want. The issue is that the atlas map is lost from GPU memory during hibirnation, so if we detect when the app comes back from hibirnation, we could make a plugin to fix this for users that experience this. 

Plugin could be made that reloads the character atlas and draws the canvas again using xterm internals, I'm not sure how to do this but I'm sure it's possible.

**Comment by thornjad** [comment]
I have experienced this problem with every electron app I've used, except, interestingly, Slack. But I have experienced it for at least a couple years. I can't find any issues submitted to Electron, Atom nor Chromium after a decent search attempt.

I do think @albinekb and @mojoaxel are right that this is something far upstream from Hyper, and might be tied to OS and/or drivers. I'm on Mint 18.3, currently using the NVIDIA driver 384.130, though I've also had the issue with Nouveau.

The problem is solved in Hyper and in Atom by simply doing something to re-render the text, like zooming or opening modal windows (like find-and-replace in Atom), and this is usually good enough for me.

**Comment by marius311** [comment]
I also suffer from the same thing, Ubuntu 18.04, Gnome 3.28.2, nvidia-driver-430 (also tested 390, 396, 415). Below is a sample of what I see. 

I do want to point out that maybe theres some motivation to try to do something on the Hyper side to ease our pain, because while I also see this same kind of corruption in other Electron apps, Hyper is unique in that I can't get rid of it with resizing, etc... nor with restarting Gnome (Alt+F2 + r) which fixes all other apps except Hyper. Reload is the only thing that works. A simple plugin that does that automatically would be much appreciated! (I've already got a script automatically reloads Gnome, but Hyper remains the lone corrupted app otherwise) 


![out](https://user-images.githubusercontent.com/1510968/58823192-f8d59100-85ed-11e9-8d48-e8f99b7b2534.gif)

**Comment by JimWhiteheadUCSC** [comment]
Just a quick note to mention that I am also experiencing this problem. I'm seeing this running Hyper from Windows 10, then running bash. My machine has both Intel graphics as well as NVidia graphics (Dell XPS laptop).

**Comment by SleepWalker** [comment]
btw. This bug is fixed in Ubuntu 19.10 and in 19.04 and 18.10 possibly too. I think this is due to new Gnome version

**Comment by szmarczak** [comment]
@SleepWalker What nvidia drivers are you using? What is your kelner version?

**Comment by SleepWalker** [comment]
@szmarczak kernel `5.3.0-24-generic` and no nvidia drivers currently :) I've forgot, that I've switched my notebook to the new one. If I'll find the time to upgrade my old laptop to the latest ubuntu, I'll re-check how does hyper work there.

**Comment by szmarczak** [comment]
@SleepWalker Then perhaps `nouveau` got fixed.
