### ISSUE TITLE
Question: Hyper Pokemon Theme missing from Hyper Store

### ISSUE THREAD

**Issue by novddd** [zeit/hyper#2898]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

## Issue

Hi! I noticed that the [hyper-pokemon](https://github.com/klauscfhq/hyper-pokemon) theme is missing from the Hyper theme store. Are themes hand-picked by the Hyper team itself or is there a way for users to submit themes themselves? Thank you for your time!

**Comment by timothyis** [comment]
This is more of an issue for the [hyper website repo](https://www.github.com/zeit/hyper-site), but I'll answer here anyway!

Simply because it didn't work at the time of creating the Hyper Store. If anyone were to submit a pull-request with hyper-pokemon now, and it works with v2, I'd be happy to accept it!

**Comment by novddd** [comment]
Awesome! I will create a issue on their github repository to let them know about it. Thank you a lot @timothyis for your info!
