### ISSUE TITLE
Cicso escape sequence not working

### ISSUE THREAD

**Issue by AlienPie** [zeit/hyper#3079]
Hi folks,

I use hyper to administer network devices a lot, and have noticed that standard cisco escape command (ctrl+shift+6/ctrl+^) doesn't seem to work. I'm not sure if this is something I can modify with the META key in the config file, or if it's a limitation with the underlying xterm.js (I'm sure I read something about this somewhere) but figured I'd ask, and it could be logged if it was something new.

Info below, thanks!

- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 2.0..0 stable
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/AlienPie/c358e07e2d999ac0717b56d511f502da

**Comment by topranks** [comment]
I am also having this problem.

It would be good if in the keymaps you could define a "passthrough" command, whereby you could define keypresses that would be sent to the terminal rather than intrepted by the application itself.

I am absolutely loving hyper, really is a great piece of software.  But this one issue is causing a lot of problems.

Thanks.

**Comment by topranks** [comment]
So I guess this is "no intention to fix" then?
