### ISSUE TITLE
Why was v3 released?

### ISSUE THREAD

**Issue by Stanzilla** [zeit/hyper#3604]
Honestly guys, I tried reaching out on Twitter but since Slack is gone, nobody seems to answer anywhere anymore. Why was v3 rushed out? And with so many known issues? We just changed the path of were settings were stored on Windows and Linux and you released this without having a migration in place? We released with super old on vulnerable dependencies? No communication about this anywhere whatsoever?

**Comment by spg63** [comment]
Is there a way to downgrade to v2.1.1? I tried installing, it auto updates. This move to v3 is an absolute disaster.

**Comment by Astrophizz** [comment]
[![image](https://user-images.githubusercontent.com/2242593/57242283-baea4a80-6ff8-11e9-8d6e-ed878c77a09d.png)](https://github.com/zeit/hyper/pull/3585)
🤔

**Comment by richardfrost** [comment]
This setting change really threw me for a loop. If anyone is confused, on windows it changed from `%UserProfile%\.hyper.js` to `%AppData%\Hyper\.hyper.js`. A warning or migration would have been nice. Personally I'd still prefer it looking in my user folder where I like to keep my dotfiles.

**Comment by fullnelson14** [comment]
Yeah I agree heavily, whose idea was to update the config file location?? I can't get the .hyper.js file to take effect, and I've moved it to the AppData/Hyper folder. Any suggestions?

**Comment by richardfrost** [comment]
@fullnelson14 I just opened the config file (Hamburger Menu > Edit > Preferences) and copied the contents from my old file. Had to restart Hyper and it took a bit for all my plugins to get installed, but it did work.

**Comment by fullnelson14** [comment]
Thank you @richardfrost, I got it working. Cheers.

**Comment by jamiebuilds** [comment]
@Stanzilla I think that this is an inappropriate way of communicating with maintainers.

Open source is something that people do for free, often in their free time, almost exclusively with very little resources. As someone who has maintained projects used by tens of thousands of people, I can testify to how hard that work is and how exhausting it is to have users berating you at the same time.

It's issues like this that have led to many maintainers burning out and quitting.

I would encourage you to apologize and to take a more constructive tone in the future.

**Comment by Stanzilla** [comment]
Nothing to apologize for here. and I am a contributor.

**Comment by jamiekyle-eb** [comment]
> Nothing to apologize for here. and I am a contributor.

I disagree, this is not an appropriate thing to do to other maintainers regardless of the amount you've contributed to a project.

Have more empathy for your fellow contributors.

**Comment by WoodyWoodsta** [comment]
This is a legitimate question, though. Was there an advertised release date that needed to be met?

Where should this be discussed then, if not here?

**Comment by no-simpler** [comment]
> @Stanzilla I think that this is an inappropriate way of communicating with maintainers.
> 
> Open source is something that people do for free, often in their free time, almost exclusively with very little resources. As someone who has maintained projects used by tens of thousands of people, I can testify to how hard that work is and how exhausting it is to have users berating you at the same time.
> 
> It's issues like this that have led to many maintainers burning out and quitting.
> 
> I would encourage you to apologize and to take a more constructive tone in the future.

As much as I agree with the point you are making, I fail to see how it is applicable to this particular issue.

Questions asked are legitimate and substantive, while perceived tone of their asking is at worst nonplussed, and in no way disrespectful. There should be balance between respecting maintainers and questioning reckless maintenance, and I feel like your position lands far off to the side.

I would encourage you to apologize and to take a more constructive tone in the future ;)

**Comment by smarts** [comment]
Related to the Hyper v3 release, I just wanted to point out that the release notes say that one of the Major Changes was an upgrade to Electron v4, but farther down under the Patches it says that there was a downgrade to Electron v3. Might want to fix that up to avoid confusion.

**Comment by michalsnik** [comment]
Tip for Windows users, you should still be able to access previous version by going to the following directory:
```
C:\Users\your_username\AppData\Local\hyper\app-2.1.2
```
There should be `Hyper.exe`

It should be possible on OSX too.

**Comment by ridhwaans** [comment]
the update reset my settings. how do I set the default shell on startup to be zsh and source zshrc on windows 10?  
Also whats the place on windows10 to configure the following? Font, Color Preset, Profiles ->Window Style, Terminal Environment  
thanks

**Comment by jagloro** [comment]
> 
> 
> the update reset my settings. how do I set the default shell on startup to be zsh and source zshrc on windows 10?
> Also whats the place on windows10 to configure the following? Font, Color Preset, Profiles ->Window Style, Terminal Environment
> thanks

https://github.com/zeit/hyper/issues/3605
@ridhwaans Check this issue how to recover your hyper.js from previous versions

Should close this ticket, update, and refer to 3605

**Comment by Stanzilla** [comment]
This issue is a discussion/feedback for the maintainers, all the issues that came up with the release can be discussed in other issues. This one is for discussing communication issues inside the team / @zeit

**Comment by samoldenburg** [comment]
Long term fan of hyper here, and feel the same.

Clearly when this release was drafted many of these bugs had to have been known, but they released anyway? Why?

**Comment by Glenn-Jaya** [comment]
Well i'm excited. I hope it's less laggy now. I use hyper on windows with git bash as the shell.
Now that i've been using vim more I've had to move to regular git bash because hyper 2 was slow.
I hope this one is faster :)

**Comment by ppot** [comment]
I was wondering the same. However I feel like I'm on the only one who has beed working on it lately. Looking at issues etc. Following this lead why was the 3 version released? Issue's where still popping up by people's using the canary version? Why saying go and update when people can just use the canary flag in their config until it's ready for merge and release?

Lately, I have been hacking on rewriting the whole core and renderer with elements on perspective.
### Here are my thoughts
1. The plugin api is a cluster. There is to much drawback with it.
2. The code has been monkey patched for plugins instead of usability and speed.
3. No code documentations on either the code structure or code orchestration.
4. Since the move to `xterm`, there is hacky behavior to past `hterm` for plugins drawbacks. But why?Since it's a plugin, it's his jobs to upgrade and update to new behavior or not. 
5. There is a decision to be made between flexibility and speed and how to do it.
6. Question's such as:
```
1. What is the plugins api for?
2. What do we want of it?
3. What extensibility should it have?
4. What flexibility should it have?
5. Coding convention?
  -> Since working on hyper I have been passing from nothing to xo to eslint.
  -> Why? Flavor of the moment?
6. Typescript?
  -> yes or no?
7. Plugin's = extensions or theme's? 
  -> There should be a distinction between the two and treated accordantly.
8. And so on...
```
7. Do we maintain it and patch it? Or we update is and upgrade it?
```
Here there is a difference between the two. 
Update and upgrade: Changing the code and introduce breaking changes.
Maintaining and patching: Keep the code and only fix issues.
meaning: Not For Plugins.
```

I could continue on and on. I hope you see the point of view here.

Also what's the utility of spectrum vs slack? On slack you could see the discussions and help. I posted a question on spectrum of what people wanted as session restorations.... Never got an answer. My work on it lead to trying to make it as a said `plugin` however the code is so monkey patched that even as a maintainer and contributor who introduced `keymap` for hyper can't seem to understand the hacking work made for plugin to use in plugin etc.

#### Overral answer:
1. @spg63 you can get it from releases here on github.
2. Config is not overwritten it's moved to new folder. As a contributor I just made a `cp x to y` but I knew of the change.
3. Reflow on resize now work. Yay 🎉

**Comment by babo** [comment]
@jamiekyle-eb Having more empathy for your users is also a sensible way of thinking. This thread is a feedback that it not worked. It's not the end of the world.

**Comment by rauchg** [comment]
@Stanzilla **I want to apologize for this, and everyone on this thread.**

I was the one to suggest to @juancampa that we release a stable. After talking to the xterm.js team, I felt like we had been keeping the new engine under wraps for too long, and the risk of unknowns was creeping up.

**We had been testing the canary for months**, so I incorrectly assessed the risk of this release, specially to Windows users.

Here's what I want to do to fix this moving forward to fix this
- Dramatically increase transparency. We need to all come together to work on this as a community. That's how it was always intended to be, and how I want it to continue.
- Make use of GitHub projects to plan releases
- Go back to using a public #hyper channel in our core Slack so that we can have realtime chats like we used to. Spectrum is good for larger public discussions, but core contributors need a place to chat more intimately.

Specially sorry to @ppot and all the people who have been contributing for long. Let's all try to make Hyper 3 a new beginning, a rock solid foundation to build on.

I have many ideas of core features that I want to bring into the project:
- Built-in search
- Built-in `hypercwd`
- Improved plugins and theming support
- Improved sandboxing and security
- Improvements to the review process of the https://hyper.is store

and much more. It's a really exciting time for Hyper.

**Comment by rauchg** [comment]
I'm going to close this in favor of more granular issues where we can discuss these action items.

To start, I created an issue to discuss goal and release cadence transparency: https://github.com/zeit/hyper/issues/3647

Would love to hear your input
