### ISSUE TITLE
RFC: Hyper 3 Migration

### ISSUE THREAD

**Issue by juancampa** [zeit/hyper#3605]
## Problem

We changed the location of the config file in Hyper 3 (Windows) without proper a proper migration path causing disruption to users updating from the stable branch.

## Workaround

If you're experiencing this issue, you can **copy** your `.hyper.js` from
```C:\Users\<username>\```
to:
```C:\Users\<username>\AppData\Roaming\Hyper```
and restart hyper.

If you keep having issues with Hyper 3 you can also temporarily [downgrade to Hyper 2](https://github.com/zeit/hyper/releases/tag/2.1.2) but **please report any issues so we can fix them in a timely manner**

## Fix

We have a couple of potential fixes:

 1. Revert the location to the previous one
 1. Detect if there's a file in the old location and copy/move it to the new location, backing up any existing ones in the new location (probably a fresh config augenerated by Hyper 3)

I think (2) is the way to go but would like to hear opinions from the community (cc: @Stanzilla, @mazyi, marekkaczkowski)

## Improving testing

Moving forward we would like to prevent this from happening again. The way to do this is by improving our testing infrastructure. We're accepting proposal to and collaboration on this front. If you're interested feel free to let me know and we can coordinate

**Comment by Stanzilla** [comment]
I vote 2,

if there already is a file in the new location, which is only the case if the user already upgraded, overwrite it but keep a backup and tell the user what happened.

**Comment by awarmfastbear** [comment]
> I vote 2,
> 
> if there already is a file in the new location, which is only the case if the user already upgraded, overwrite it but keep a backup and tell the user what happened.

How about if there's already a configuration in the old location, use that in the new location.

Would of been nice to have this config location change pointed out at the top of the Notes as it is a disruptful change.

It was pretty confusing to me to upgrade and see that my config in the old location is doing nothing. Had to look at Github to find this nice related issue.

**Comment by mhall** [comment]
I would vote for using the new AppData location by default, and if nothing is found there, use the old location as a fallback _without_ any copying or migration. If there was a popup notification asking users to choose whether to migrate or not, that would be even better. I understand the "best practice" argument for the introduction of the AppData location, but as I keep my configuration files in a git repo checked out to my home directory, personally I would prefer to keep using the former path without having to resort to symlinks.

**Comment by MaxySpark** [comment]
After updating to v3 when I use clear command it doesn't work properly. I need to scroll up and down to apply the clear effect.
In v2 I didn't get this issue.

**Comment by richardfrost** [comment]
This is probably by design, but I'm getting this message:
```
Uncaught Exception:
Error: EPERM: operation not permitted, symlink
```

It looks like fix 2 is trying to move the file, but that is failing if it's a symlink. I can fix this myself by just moving it manually, or just deleting that symlink, but I just wanted to point out that this situation wasn't being handled.

I have mine as a symlink because I have a dotfiles git repo that I sync between computers and my setup script right now just symlinks my dotfiles into my `~` or `%UserProfile%` by default. I can adjust it so it points Hyper's config symlink over to `%AppData%\Hyper`. I was wondering if its worth detecting if it's a symlink during the migration, and if it is create a new symlink in the `%AppData%\Hyper` folder with the same target as the existing one, and then remove/rename the original symlink in `%userprofile%`?

If I'm in the minority, which I probably am, just ignore this comment.

**Comment by juancampa** [comment]
The latest stable shouldn't do anything if a file is a symlink due to potential edge cases

**Comment by juancampa** [comment]
Closing via 3.0.2
