### ISSUE TITLE
5bc8e0b (on canary) breaks <esc> key

### ISSUE THREAD

**Issue by lispy** [zeit/hyper#3929]
- [ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Linux
- **Hyper.app version**: 6f96d9f (latest commit on canary branch)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue
Commit 5bc8e0b introduces in each of the `app/keymaps` files the properties `editor:search` and `editor:search-close`. The value for the latter, `"esc"`, is unfortunate because it's global, is an extremely relevant key for `vim` users, and also factors into terminal shortcuts (at least when using `bash`).

Might it be possible to enable `editor:search-close` only when actually searching? This would keep it from interfering when not using the search feature. Alternatively, might a different key sequence be used (such as `shift+esc`)?

**Comment by Stanzilla** [comment]
@El-Dringo-Brannde what do you think?

**Comment by ivanwonder** [comment]
I agree with @lispy, this is why I cannot exit the edit mode of vim. I thought it was the problem of vim before.

**Comment by iEricKoh** [comment]
same problem happen to me

**Comment by mccartney** [comment]
It also affects `Esc-0` terminal codes for `F10` (and my ability to exit Midnight Commander :P)

**Comment by LabhanshAgrawal** [comment]
I looked into this a bit and thought about the possible solutions (including already mentioned ones)

**using `shift+esc`**
easy to do, might not be intuitive at first for users

**capture `esc` only when search is open**
best case scenario, I tried to come up with some genric way where commands would be able to return a value indicating whether the event should be caught or not. But as the commands go through
`mousetrap`>`renderer rpc emit`>`ipc send`>`main rpc emit`>`execCommand`>`webcontents send`>`renderer rpc on`>`store dispatch`
it seems a bit hard to do while keeping it generic and without impacting plugins.
- One way to do this specifically for search could be to dispatch the search close action from the mousetrap bind call with a reference to the keyboard event and setting `e.catched` as `false` if the search bar is already closed. This can be done directly without going through ipc as the main process doesn't really do much for this command.
- This could be done with a commandHandler also instead of putting it in the mousetrap bind call

**Let `esc` event go to both xterm and search box**
We can set `e.catched` as `false` when the command key is `esc` this would cause both search box to close and xterm to get the `esc` event. though this might cause accidental `esc` keys for people who just wanted to close the search

@Stanzilla @ivanwonder what do you guys think about this.

---
P.S. While reasearching this I noticed that most of the commands don't really need to be passed to ipc as main process just emits them back (with changed name), We can also consider putting these commands in a separate list and emitting them directly.

One other thing to consider for the 3rd option is putting special keys/combos which are commonly needed by terminal e.g. esc, ctrl+c, ctrl+d etc. in a list and letting them go to both xterm and commands.

**Comment by Stanzilla** [comment]
I like the only capture when search is open solution

**Comment by LabhanshAgrawal** [comment]
What approach do you think we should use to implement that solution.

Also any thoughts on the stuff in P.S. ?

**Comment by bet4it** [comment]
How does [hyper-search](https://github.com/jaanauati/hyper-search) implement it?

BTW, I think `hyper-search` is much beautiful than this implement.

**Comment by Stanzilla** [comment]
Don't really know atm :/

**Comment by LabhanshAgrawal** [comment]
> How does [hyper-search](https://github.com/jaanauati/hyper-search) implement it?
> 
> BTW, I think `hyper-search` is much beautiful than this implement.

Agreed, it looks better. But it'd be a bit more work to replicate it compared to fixing the `esc` thing now. Maybe we can take a look at it later.

**Comment by bet4it** [comment]
Do we really need to merge it if we could achieve it by a plugin?
We could just revert it!

And this implement would confuse `hyper-search` user.

**Comment by Stanzilla** [comment]
In my opinion this feature should and always should have been baseline

**Comment by LabhanshAgrawal** [comment]
I also think that search should be provide out of the box, And using xterm search method seems better than the custom implementation in hyper-search.

**Comment by ivanwonder** [comment]
The second solution that captures `ESC` looks good for me.

**Comment by LabhanshAgrawal** [comment]
> The second solution that captures `ESC` looks good for me.

can you try out #4407 once

**Comment by ivanwonder** [comment]
@LabhanshAgrawal error when running `yarn` in your project 😂.
`Error: Generated checksum for "chromedriver-v8.0.0-darwin-x64.zip" did not match expected checksum.`

**Comment by LabhanshAgrawal** [comment]
> @LabhanshAgrawal error when running `yarn` in your project 😂.
> `Error: Generated checksum for "chromedriver-v8.0.0-darwin-x64.zip" did not match expected checksum.`

That's a spectron installation issue, see https://github.com/electron-userland/spectron/issues/265

**Comment by svenjacobs** [comment]
Any chance to get a new canary version that contains the fix to this problem?
As a Vim user I really need the ESC key :/

**Comment by LabhanshAgrawal** [comment]
> Any chance to get a new canary version that contains the fix to this problem?
> As a Vim user I really need the ESC key :/

Not sure about a release. You can get the latest ci build from https://github.com/vercel/hyper/actions/runs/136614828

**Comment by admosity** [comment]
This comment got my esc key working again on the canary channel:

https://github.com/vercel/hyper/issues/3217#issuecomment-646773120

Adding this to the config
```javascript
  keymaps: {
    'editor:break': 'esc',
  },
```

**Comment by egst** [comment]
`editor:break` does `ctrl+c`, but I think `ctrl+[` would be more useful. In Vim, `esc` and `ctrl+[` are equivalent, while `ctrl+c` is slightly diferent. It's not a major problem in Vim but it definitely is a problem in a shell with Vi mode as `ctrl+c` has a completely different meaning in this context. Mapping `esc` to `ctrl+c` makes it impossible to switch to the command mode in a vi mode shell with the `esc` key. Is there currently any way to map `esc` to `ctrl+[`?
