### ISSUE TITLE
Update update notification

### ISSUE THREAD

**Issue by timothyis** [zeit/hyper#460]
As requested by @rauchg:

So I was initially asked to increase the contrast between the text and the background of the update notification, but then I started posting things to the Zeit Community slack and we came up with some cool things.

Feedback from the community concluded that the update notification was intrusive and hid important pieces of the terminal when open. So we came up with a remedy.
<details>
<summary>

Icon, Hover to see details and Contrast update</summary>

An icon to notify the user of the update and hovering to see the update information and to restart:
<img src="https://cloud.githubusercontent.com/assets/1695613/17178279/1eeb5540-5415-11e6-8179-aadd3b9a2cb9.png" width="470" height="359">

Co-existing with other notifications:
<img src="https://cloud.githubusercontent.com/assets/1695613/17178475/e9c09cc6-5415-11e6-8f6a-8a07d1ab38fc.png" width="470" height="359">

On hover of the icon:
<img src="https://cloud.githubusercontent.com/assets/1695613/17178323/4d3352ea-5415-11e6-92b1-d2663fcd122e.png" width="470" height="359">

For Linux:
<img src="https://cloud.githubusercontent.com/assets/1695613/17178710/c974e430-5416-11e6-95e3-fe638fedac7f.png" width="470" height="359">

</details>

And then I went a little bit further as to save more space and updated the icon via @leo. (thanks!)

<details>
<summary>

More space, more beauty?</summary>

Icon:
<img src="https://cloud.githubusercontent.com/assets/1695613/17178558/3e561464-5416-11e6-9ce2-f853a9383656.png" width="470" height="359">

Hover:
<img src="https://cloud.githubusercontent.com/assets/1695613/17178569/4b12ffb4-5416-11e6-90ba-f5a5cdd8993e.png" width="470" height="359">

Linux:
<img src="https://cloud.githubusercontent.com/assets/1695613/17178593/5fa1ab74-5416-11e6-948b-ceacf97d71aa.png" width="470" height="359">

Co-existing:
<img src="https://cloud.githubusercontent.com/assets/1695613/17178625/72bfffda-5416-11e6-8e91-26fd733a1b0a.png" width="470" height="359">

</details>

Please share your thoughts!

**Comment by leo** [comment]
> More space, more beauty?

I'm not able to express how beautiful this part looks. Combined with the `max-width` of `calc(100vw - 14px)` for each of these notifications, they also won't overflow out of the viewport. This concept is just perfect, IMO!

@CodeTheory and I tried to evaluate it on slack. Bought the icon from [TheNounProject](https://thenounproject.com).

**Comment by rauchg** [comment]
I like thinner icons personally

**Comment by leo** [comment]
Let's replace it then! :blush: After looking at it again after some time, it really looks a little thick.

@CodeTheory Send me the link on Slack if you want another NounProject icon, I'll get it!

**Comment by rauchg** [comment]
My only concern with the bottom right notification approach is that it doesn't lend itself well to a cohesive cross-platform experience.

I think it looks particularly good because of the `border-radius` but that's not gonna be there in linux and windows, where the separation will look better.

**Comment by CodeTheory** [comment]
@rauchg I agree, though I do share my thoughts with others such as @leo who say that the floating notification take up a lot of, what could be, important space.

It's not a big deal if it doesn't get used. It's exactly why I created both versions, so we had options. 😄

**Comment by rauchg** [comment]
Yep that's why i definitely love the evolution we've made with regards to the "collapsed" state of the update notification. And I think an icon that indicates "update" is better suited for that collapsed state than the checkmark, so double win.

What I would like to see is the actual animation in action to make sure it actually works, specially when other notifications are transiently present. The next step I think is to codepen it up.

**Comment by CodeTheory** [comment]
I was actually going to prototype is in framerjs since we then don't need to recreate the entire app styling etc. I'll post it here when I've done it.

**Comment by CodeTheory** [comment]
I'm going to have the prototype started/possibly done by tonight.

**Comment by CodeTheory** [comment]
Okay, here's an update!

- The point of this task in the first place was to improve contract. Even though I achieved better contrast, it still wasn't great for everyone.
- I decided to a custom icon rather than purchasing them or using free ones since it's easier to cater to the collaborators needs if an update is necessary. 

<details>
<summary>New text colour, new icons</summary>

Notification on it's own:
<img src="https://cloud.githubusercontent.com/assets/1695613/17302496/c971149a-581c-11e6-8a55-a976066e3fce.png" width="470" height="359">

Expanded notification (Auto-update):
<img src="https://cloud.githubusercontent.com/assets/1695613/17302531/f2061ea0-581c-11e6-92ce-149527c8cb54.png" width="470" height="359">

Expanded Notification (Linux):
<img src="https://cloud.githubusercontent.com/assets/1695613/17302540/043ff866-581d-11e6-8169-75ca6d002b90.png" width="470" height="359">

Co-existing with other notifications:
<img src="https://cloud.githubusercontent.com/assets/1695613/17302578/281efa5c-581d-11e6-9696-c76e3ffbcd8b.png" width="470" height="359">

</details>

And finally, we have a prototype made in framer showing off an animation when the notification appears, is mouse-overed, and `restart` is clicked:

![hyperterm-update-notification](https://cloud.githubusercontent.com/assets/1695613/17302747/ebe518cc-581d-11e6-8fa8-acbf1a51ed9d.gif)

**Comment by CodeTheory** [comment]
Update #2:

Gif featuring a co-existing notification. 
<img src="https://cloud.githubusercontent.com/assets/1695613/17349060/371f9a4e-591b-11e6-9fe0-c81238a69bcb.gif" width="640" height="387">
