### ISSUE TITLE
Name schema for plugins and extensions

### ISSUE THREAD

**Issue by leo** [zeit/hyper#494]
Since most (if not all) of the projects within the node ecosystem are using this technique, I think we should adapt it in favour of making the experience consistent for all users:

`hyper-<name>`
## 

What I'd like to do is modify the existing "plugins" array within the config file. This way, the user only needs to enter the name of the plugin and the string will automatically get prefixed behind the curtains and downloaded from npm:

``` js
plugins: [
  'links',
  'blink',
  'cwd'
]

```

Results in these packages getting installed:
- hyper-links
- hyper-blink
- hyper-cwd

**Comment by lordgiotto** [comment]
Completely agree with your analysis, and I would strongly prefer **technique 1** :)
The only problem that has to be faced is about the existing plugins, since npm doesn't allow renaming published packages.

**Comment by leo** [comment]
@lordgiotto Cool!

What we would do in this case is re-publish all existing packages under the new, correct name. And within HyperTerm itself, the old ones will simply continue to work until the whole community made the switch in their config.

How? I'd say checking if the plugin/theme name starts with "hyper", it simply won't be prefixed automatically it gets installed.

**Comment by dak0rn** [comment]
What about internal/private packages, not hosted on the official npm registry or on a npm registry at all. npm [supports installing from git or arbitrary tarballs](https://docs.npmjs.com/cli/install).
If there is auto-prepending of a `hypterterm-` prefix, there should also be a check for the other possibilities, I'd say.

**Comment by leo** [comment]
@dak0rn Agreed! We'll only auto-prefix it if it's a normal package hosted on npm. So if it starts with a `@` or contains a `/`, we'll just pass it through to npm.

**Comment by dak0rn** [comment]
@leo Maybe you should also add `path.sep` to the list, as the dependency can also be a file path.

**Comment by leo** [comment]
@dak0rn All locals plugins should be located in `~/.hyperterm_plugins/local/`. If you don't want to put your directory there, you can [link](https://github.com/matheuss/hpm/issues/18) it.

**Comment by dak0rn** [comment]
Sorry, I might have been a bit unclear. If I got the config correctly, then `plugins` is the list of npm dependencies that are installed into the very folder you mention. What I wanted so say is that npm is able to install from file locations, e.g. from a tarball on a shared network device, and if you want to support both prefixing and all possible npm install paths in `plugins`, you should add support for file paths. Therefore, `path.sep` because there's this fancy backslashy operating system.

**Comment by leo** [comment]
@dak0rn Ahhh! Yea, I think that's actually a great idea. 😊

**Comment by dak0rn** [comment]
I think, though, that this is sufficient to flip the condition, that is, detecting plugin names that have to be prefixed.

`const needsPrefix = str => !! str.match(/^(?!hyperterm-|hyper-)[\w-]+(#.+)?$/i);`

Check [this regex101](https://regex101.com/r/zN9vL8/1) for an example.

**Comment by chabou** [comment]
I think it is a bad idea to mask plugin name.
It reminds me loader from webpack v1 when `loader` in name was optional in config file.
It can have some (rare) name collision. It can be tricky to understand why a `revolution` plugin is not loaded because a `hyper-revolution` exists.

Too few pros to make a difference between a plugin name and what to add in configuration imho.

**Comment by MartyGentillon** [comment]
It's also worth noting that atom does not do this.  I don't think that the standard is followed well enough for it to be relied on.

**Comment by Stanzilla** [comment]
I think we agreed on not doing this
