### ISSUE TITLE
PR: Use Preact in production for faster initialization

### ISSUE THREAD

**Issue by amilajack** [zeit/hyper#525]
Willing to make a PR for this.

**Comment by matheuss** [comment]
Could you, please, elaborate more on it? What's some pros and cons? 😅

**Comment by amilajack** [comment]
[Preact](http://github.com/developit/preact) is a lightweight implementation of the public react API. It is able to initialize faster because its much lighter in weight because it doesnt support older react APIS.

@developit

**Comment by matheuss** [comment]
> its much lighter in weight because it doesnt support older react APIS.

That's neat

**Comment by developit** [comment]
I had a branch here. Seemed to be working quite nicely:

https://github.com/developit/hyperterm/tree/preact

Would need to be updated/rebased since this was forked a few weeks back.

**Comment by krzkaczor** [comment]
It sounds interesting. Is there any existing case study of doing something similar?

**Comment by developit** [comment]
@krzkaczor There are quite a few examples. Here are three:

https://github.com/ubilabs/react-geosuggest/pull/103
https://github.com/developit/hn_minimal
https://github.com/developit/preact-compat-example

Certainly not exhaustive case-studies, but the conclusion is unanimously the same.

**Comment by ajhyndman** [comment]
I'e got a small amount of experience with Preact.

One big downside that I've encountered is that Preact offers none of the [Synthetic Event](https://facebook.github.io/react/docs/events.html) normalisation you get in React.  Preact also doesn't offer the ES6 class based API for components, nor [flow-type definitions](https://github.com/developit/preact/issues/219).

I don't know how important any of these are for HyperTerm, but I think those are a couple caveats to be aware of.

**Comment by developit** [comment]
Sorry for dropping this issue on the floor! I just felt I should try to clarify a couple things:

I think the recommendation was to use `preact-compat`, which includes PropType validation, and supports an identical interface to React allowing the use of the existing Flow definitions.

Synthetic Events is indeed an implementation difference. However, it's actually rather unnecessary for web content - particularly in the case of Electron where the target browser is controlled and constant. In this case (and in most evergreens), using a completely custom event system is simply unnecessary complexity.

The branch I linked above, though now quite outdated, demonstrates that there are no issues in porting the code over. 

Not meaning to push for anything here since I'm prone to bias, just wanted to clear those things up! 

 I recall chatting with @rauchg a while back and he noted that there are a relatively small number of actual React components in Hyperterm, since the terminal rendering is handled by hterm (maybe this has changed). I would imagine the value of preact here would be that, if component rendering is a small part of the application compared to state management and the terminal emulation, it might make sense to use a correspondingly small component rendering implementation.

Just my random thoughts on the matter!

**Comment by iamstarkov** [comment]
afaik preact doesnt implement synthetic events system, so we cant talk about 100% match

**Comment by iamstarkov** [comment]
can someone try to bench current react implementation? just so we know performance statistics at the start

**Comment by lucsky** [comment]
If what you are looking for is pure performances then [Inferno](https://github.com/trueadm/inferno) blows both React and PReact out of the water.

**Comment by developit** [comment]
@lucsky where did you infer this was a performance suggestion? The goal was to load less script.

**Comment by lucsky** [comment]
@developit Oh, damn, you're right, I was way too quick reading the title of this issue, I stopped at "faster" and missed the "initialization"... Ooops. Sorry about the noise.

**Comment by rauchg** [comment]
Yeah for the tests we ran, Preact yielded much faster initialization due to smaller script. Probably not a noticeable diff for render, since hterm uses a different non-diff system.

I'm interested in revisiting Preact, insofar we can maintain good compatibility with plugins.

**Comment by developit** [comment]
yup yup. I can take a crack at an updated PR for this once I've published `7.2`.

**Comment by CodeTheory** [comment]
There hasn't been activity on this issue for quite some time. Unless someone wants to take a shot at this, I think we should close it.

**Comment by albinekb** [comment]
I think we should explore switching to preact now that the renderer (xterm) is canvas based. Our UI is the only thing being rendered by react, so we could probably get a nice speedup and size reduction by switching to Preact.

**However** there could plugins that depend on full React being available, so this should be tested/thought through before switching.

Are the slight startup time reduction worth breaking some plugins?
