### ISSUE TITLE
Hyperterm doesn't display Korean characters. 

### ISSUE THREAD

**Issue by hidros3** [zeit/hyper#586]
on El Capitan 10.11.5

Korean characters are displayed as "???". You can compare with iTerm's displaying. If you need further information please let me know

![2016-08-07 21 18 44](https://cloud.githubusercontent.com/assets/1088499/17462351/24e7958e-5ce5-11e6-9385-9f678f2e562c.png)

**Comment by c0b41** [comment]
probably #441

**Comment by Snack-X** [comment]
More detailed informations about this:

This is an output from **Hyperterm 0.8.3, macOS 10.12.1**, which displays Korean and Japanese incorrectly:
![output-hyperterm](https://cloud.githubusercontent.com/assets/1373527/20748080/2d3ee048-b730-11e6-9577-395e0ae724b1.png)

and this is a correct output from iTerm:
![output-iterm](https://cloud.githubusercontent.com/assets/1373527/20748074/28b4990a-b730-11e6-9da5-4ea8a81796f3.png)

This issue comes from macOS's unicode normalization on filenames.

macOS uses NFD normalization, so multiple characters makes one complete character.

```
$ ls hyperterm-test-korean
한글.txt

$ echo "한글.txt" | xxd
00000000: ed95 9cea b880 2e74 7874 0a              .......txt.
# 0xED959C = U+D55C = '한'
# 0xEAB880 = U+AE00 = '글'

$ ls hyperterm-test-korean | xxd
00000000: e184 92e1 85a1 e186 abe1 8480 e185 b3e1  ................
00000010: 86af 2e74 7874 0a                        ...txt.
# 0xE18492 = U+1112 = ㅎ
# 0xE185A1 = U+1161 = ㅏ
# 0xE186AB = U+11AB = ㄴ
# 0xE18480 = U+1100 = ㄱ
# 0xE185B3 = U+1173 = ㅡ
# 0xE186AF = U+11AF = ㄹ

$ ls hyperterm-test-japanese
がざ.txt                     ...txt.

$ echo "がざ.txt" | xxd
00000000: e381 8ce3 8196 2e74 7874 0a              .......txt.
# 0xE3818C = U+304C = が
# 0xE38196 = U+3056 = ざ

$ ls hyperterm-test-japanese | xxd
00000000: e381 8be3 8299 e381 95e3 8299 2e74 7874  .............txt
00000010: 0a                                       .
# 0xE3818B = U+304B = か
# 0xE38299 = U+3099 = <COMBINING KATAKANA-HIRAGANA VOICED SOUND MARK>
# 0xE38195 = U+3055 = さ
# 0xE38299 = U+3099 = <COMBINING KATAKANA-HIRAGANA VOICED SOUND MARK>
```

Somehow this is not normalized and displayed only first portion, `ㅎㄱ` and `かさ`.

This can be normalized with `String.prototype.normalize`:

```
> koreanNFD = "\u1112\u1161\u11ab\u1100\u1173\u11af"
'한글'
> [...koreanNFD.normalize("NFC")].map(c => c.charCodeAt(0).toString(16))
[ 'd55c', 'ae00' ]

> japaneseNFD = "\u304b\u3099\u3055\u3099"
'がざ'
> [...japaneseNFD.normalize("NFC")].map(c => c.charCodeAt(0).toString(16))
[ '304c', '3056' ]
```

Hope this information is helpful!

**Comment by BasixKOR** [comment]
Same on windows

**Comment by timothyis** [comment]
This should be fixed now! Let us know if the issue still persists 🤞

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

Continue discussion here: https://github.com/zeit/hyper/issues/2322
