### ISSUE TITLE
Serializable terminal state

### ISSUE THREAD

**Issue by rauchg** [zeit/hyper#781]
Right now we're deferring to hterm for terminal rendering. This has worked fantastically well, but has the major drawback that hterm's implementation is very dependent on the rendering logic and the DOM.

We need to transition into a system that allows us to separate the terminal _data_ from its _rendering_.
In other words, the state of the terminal, such as the visible rows and columns, caret position, active ANSI modes and scrollback should live in reducers.

A strong candidate to transition into is Terminal.js by @gottox, who's also the author of `child_pty`. Here's some of its relevant documentation: http://terminal.js.org/TermState.html

**Comment by rauchg** [comment]
One of the nice advantages of this would be the ability to trivially re-instantiate terminals after re-renderings (i.e: very clean hot code reloading), or even move a session from one window to the other (through drag and drop for example).

**Comment by Tyriar** [comment]
FYI [xterm.js](https://github.com/sourcelair/xterm.js) is about to go through a refactor to achieve something like this in order to enable the tty to exist and function entirely without being attached to the DOM (https://github.com/sourcelair/xterm.js/issues/266) to better support the terminal API in vscode (https://github.com/Microsoft/vscode/issues/12000).

**Comment by rauchg** [comment]
That sounds great! Definitely a great option then.
