### ISSUE TITLE
Linux download link not working

### ISSUE THREAD

**Issue by omazhary** [zeit/hyper#801]
Going to [the official download link](https://hyper-updates.now.sh/download/linux) results in the following weird error message:
```
Version not found: latest
```

**Comment by matheuss** [comment]
#799 😄

**Comment by saule1508** [comment]
@matheuss 
Please note that the download link is still broken but the issue #799 is closed for comment so I mention in here. There is probably some misunderstanding:  it is really only about changing the web site download link to make it point to the correct destination.

**Comment by kleinfreund** [comment]
@saule1508 I believe the maintainers/collaborateurs are well aware of the situation. Quoting from the aforementioned issue #799:

> We can't fix it for past releases 😕 It'll be fixed on the next one – which will be shipped very soon 😄

**Comment by saule1508** [comment]
@kleinfreund indeed, but I was wondering what release he speaks about (a release of hyper or a release of the zeit website ?). Because fixing the download page on the web site is all what is needed, it should take 1 minute for someone that has access. It is really a quick win because currently it is not easy at all to know that the app can be run in any linux distro via the appimage (and not only debian as mentioned on the web page). It is just a pity for those users that cannot use this fantastic app !

**Comment by ppot** [comment]
@saule1508 @kleinfreund it's about hyper.app release. Not the website release.
