### ISSUE TITLE
CSS selector `.tab_active` is not working anymore

### ISSUE THREAD

**Issue by iDams** [zeit/hyper#806]
Hey, since recent updates of hyper, it seems like the `.tab_active` selector is not working anymore.
I'm using `hyperterm-material` plugin which has this line in `css` section:
```
.tab_active::before {
        border-bottom: 2px solid #009688;
      }
```

I also tried to add this line in my `.hyper.js` in the `css` section like this:
```
   // custom css to embed in the main window
    css: `.tab_active {
        border-bottom: 2px solid #009688;
      }`,
```

I'm looking to do this:
![hyperterm-material](https://cloud.githubusercontent.com/assets/1591702/19182505/c879c2d6-8c73-11e6-8f4c-0631d4f4ac0f.png)

Thanks!

**Comment by jamsinclair** [comment]
Perhaps try removing `hyperterm-material` plugin and reinstalling 😸

hyperterm-material has since fixed this. They moved the style to target the selector `.tab_textActive` (https://github.com/dperrera/hyperterm-material/commit/f5cf9c4f3e27d74038a08345cf50a60ac65c3370)

The tab elements have an inline style attribute for `border-color` that now trumps the css rule in the old theme. Your custom css example would work if you threw in an `!important` e.g. 
```
  css: `.tab_active {
        border-bottom: 2px solid #009688 !important;
  }`,
```

**Comment by iDams** [comment]
It worked! Thanks!
