### ISSUE TITLE
Packaged executable should be lowercase

### ISSUE THREAD

**Issue by niedzielski** [zeit/hyper#823]
Hello! This is a feature request to rename the Hyper executable a lowercase "hyper". The current name is "Hyper". In OS X's Spotlight and similar tools, search is case-insensitive and finding the app is intuitive. However, in Bash and launchers that use strict PATH lookup, only a lowercase name is intuitive. I know launching from Bash probably isn't that common but there are many launcher implementations available on Linux. Please consider this name for the launcher use case and convention's sake or perhaps packaging a lowercase symbolic link. Thank you!

**Comment by rauchg** [comment]
Do any other apps do this? Wouldn't it make more sense to `ln` manually for your case?

**Comment by niedzielski** [comment]
The only prominent Linux packages I can think of having uppercase executable names are Xorg and VirtualBox (the latter has a lowercase symlink). I'm certain there are other examples and the fix for my system is trivial as you pointed out. However, lowercase naming is prevalent by far and I felt it was more appropriate to raise this idea at the source so it could be a intuitive, "don't think about it" benefit for everyone. Thank you for your consideration of this bike shed topic :]

**Comment by jacobmischka** [comment]
This is a pretty common problem with electron apps. [Google Play Music Desktop Player][1]'s binary is `Google Play Music Desktop Player` after building, the maintainer of the AUR package [renames it][2] during installation. Brave's build tool [renames the package][3] when building for Linux.

Basically that means it's pretty much your call whether you make it lowercase for us or not. It would be nice of course, but it's not really expected since by default every electron app is this way.

[1]: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-
[2]: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gpmdp#n45
[3]: https://github.com/brave/browser-laptop/blob/master/tools/buildPackage.js#L110

**Comment by niedzielski** [comment]
@jacobmischka, thanks for the insight and the references. I believe Hyper uses electron-builder for packaging? If that's the case, should this issue be closed as a duplicate or put in tracking of the upstream bug, electron-userland/electron-builder/issues/806?

**Comment by niedzielski** [comment]
:+1: electron-userland/electron-builder#806 was only recently resolved but somehow this appears to already be fixed
