### ISSUE TITLE
select Up, Down, Left and Right panes

### ISSUE THREAD

**Issue by iamstarkov** [zeit/hyper#828]
right now its only prev/next pane, the same as tabs. Its enough for tabs, because tabs are one dimensional array.

But as far as panes are two dimensional feature, we need to navigate between them in all four sides: go to up/down/left/right pane.

**Comment by OJFord** [comment]
I was going to suggest numbers when I found this - I don't use prev/next for tabs, and the Ctrl-Option[-Shift]-Tab shortcut to do so for panes is particularly awkward.

Cmd-N to choose a tab and Option-(*numbers appear on panes*)-N to choose a pane would be great though.

I'm not suggesting it instead of directions, but directions instead of tabbing, and by-numbers available for panes too would be :+1:.

**Comment by iam4x** [comment]
I like the iTerm2 shortcuts:

* Cmd+left arrow, Cmd+right arrow navigates among tabs. So does Cmd-{ and Cmd-}.
* Cmd+number navigates directly to a tab.
* Cmd+Option+Number navigates directly to a window.
* Cmd+Option+Arrow keys navigate among split panes.
* Cmd+] and Cmd+[ navigates among split panes in order of use.

source: https://www.iterm2.com/documentation-one-page.html

**Comment by spirosikmd** [comment]
I think the last point is the most important regarding UX

`Cmd+] and Cmd+[ navigates among split panes in order of use`

Now we need to use 

```
selectNextPane: 'Ctrl+Alt+Tab',
selectPreviousPane: 'Ctrl+Shift+Alt+Tab'
```

I don't know about others, but for me this is difficult.

**Comment by spro** [comment]
I like how tmux does it, where there is a single shortcut to toggle between the latest 2 panes.

**Comment by joshschmelzle** [comment]
Just to add, under Windows 10, Ctrl + Alt + Tab is another alternative for Alt + Tab. It is a cross between Windows + Tab and Alt + Tab. It keeps the task switcher on the screen but does not include any ability to manage desktops. Ctrl+Alt+Tab. 

So, for me under Windows 10 (version 1511 build 10586.679), Ctrl + Alt +Tab brings up the task switcher and does not navigate between split panes.

**Comment by langri-sha** [comment]
Ctrl+Alt+Tab and Ctrl+Shift+Alt+Tab do not work under Gnome, as they're assigned by the window manager for switching panels.

If anyone is interested in releasing theirs to use Hyper, run `dconf-editor` and disable these two keybindings by overriding the defaults and configuring `[]`:

![image](https://cloud.githubusercontent.com/assets/77084/21307383/8ca1260a-c5d5-11e6-9b82-0a89cf1c45aa.png)

**Comment by chabou** [comment]
I'm currently trying to achieve this navigation.
I think that the best keybindings to navigate are `Ctrl+Alt+<Arrow>` if we keep `Ctrl+Alt+Tab`for `moveNextPane()` (Discussed here https://github.com/zeit/hyper/pull/1113)

This feature of navigation should be for example, starting from pane1 :
pane1 ⬇️  pane2 ⬇️  pane3 ➡️  pane4 ➡️  pane5 ➡️  pane7 ⬆️  pane6 ⬅️  pane5 ⬅️  pane1

![capture d ecran 2017-01-01 a 14 41 15](https://cloud.githubusercontent.com/assets/4137761/21581507/2175ad9c-d034-11e6-98d5-d17e980205a9.jpg)


We must keep a virtual position of a "focusPoint" in order to have 'pane5➡️pane7' move because focus was on pane4 before pane5.

The rules of moving this point of focus would be:
* When a pane is directly chosen (with a mouse click, for example), this focusPoint is set to the center of this pane. Same if a resize occurs. (Maybe after a delay too)
* When a transition is made along x-axis
  * x-coord of focusPoint is set to the center of the next pane. 
  * y-coord of foucsPoint is set to the center of the next pane ONLY if next pane border is totally included in previous pane border ('pane2⬇️pane3' but not 'pane4➡️pane5')
* Same behavior along y-axis
* Next pane chosen is the first intersected by moving this point of focus on the desired direction.
  * If point of focus intersect 2 panes (when 'pane2⬇️' for exemple), priority is left or top pane. 

For previous sequence,  point of focus is moving like this:
![focuspointmove](https://cloud.githubusercontent.com/assets/4137761/21582098/113d9dc4-d04b-11e6-81ad-79bf0901b4bc.jpg)

To achieve this, if will be simpler to have absolute frame (origin and size) of each TermGroup. These positions will be expressed in term of proportion. RootTermGroup's frame will be `{x: 0, y: 0, w: 1, h: 1}` and pane4 `{x: 0.166, y: 0.666, w: 0.166, h: 0.333}` in previous example.

As discussed here https://github.com/zeit/hyper/issues/1143, should it be a (core) plugin ? Even adding an absolute position of each TermGroup (which could be eventually useful for other features ?)

**Comment by chabou** [comment]
@matheuss @ekmartin @rauchg @CodeTheory @albinekb : can one of you, give me an advice where all of this should take place ? plugin, future core-plugin, PR...

**Comment by ppot** [comment]
Don't forget me ? Huh

**Comment by chabou** [comment]
Ouuups :) your advice is really welcome too, of course 😄

**Comment by asbjornenge** [comment]
Would :heart: to see this implemented. Please consider making the keybindings configurable :tada:

**Comment by samirotiv** [comment]
Just went through this thread. I think indeed, #1295 is far more efficient.

**Comment by chabou** [comment]
And maybe easier to develop 😛

**Comment by samirotiv** [comment]
Haha, definitely :D

**Comment by chabou** [comment]
Made with a plugin : https://github.com/chabou/hyper-pane
Feedback warmly welcome

**Comment by iamstarkov** [comment]
@chabou thanks for this

**Comment by iamstarkov** [comment]
so, this issue can be closed
