### ISSUE TITLE
Local config should take priority over plugins

### ISSUE THREAD

**Issue by OJFord** [zeit/hyper#832]
Currently, it seems that plugins override any local settings.

I would like to load the solarized dark theme plugin, but override the background colour, since I cannot read the blue against it at all (possibly related to colour-blindness) and it also jars with vim-solarized, which uses a different base colour for the background.

However:

``` js
module.exports = {
    config: {
        backgroundColor: '#ffffff', // just to be absolutely sure
    },
    plugins: {
        'hyperterm-solarized-dark',
    },
}
```

is identical to just loading the plugin - the `backgroundColor` setting has no effect.

**Comment by iamstarkov** [comment]
are you sure its not `hyperterm-solarized-dark`'s fault?

**Comment by OJFord** [comment]
@iamstarkov No idea, but it doesn't look like it:
https://github.com/Ghosh/hyperterm-solarized-dark/blob/master/index.js

**Comment by snikobonyadrad** [comment]
Same here. Using [hyperterm-electron-highlighter](https://github.com/mmcbride1007/hyperterm-electron-highlighter) but cannot change `cursorColor`. How the settings can be overridden?

**Comment by joshbetz** [comment]
I think the way `getDecoratedConfig` and `decorateObject` work are what would need to be fixed. https://github.com/zeit/hyper/blob/993b8f6833bffe75032e9f161fd17bed0c98ed73/app/plugins.js#L331-L344

**Comment by chabou** [comment]
I do not agree with that. If a plugin doesn't offer a way (ie. config) to override its behavior which do not fit your needs: maybe do not use it.
If we change plugin order, some plugin cannot work at all because its settings/behavior will always be overrided by default config. But you're right: good plugins, even theme plugins, should let user override its parameters. Maybe we should recommend it somewhere in plugin API documentation.

Maybe this plugin can help you: https://github.com/amio/hyperterm-final-say

**Comment by OJFord** [comment]
I see what you're saying @chabou, but it's a pretty confusing UX to explicitly set an option, and observe the option to be other than set.

That 'final-say' plugin looks right, but IMO this should be default behaviour.

> some plugin cannot work at all because its settings/behavior will always be overrided by default config.

I don't understand this at all - if my settings are overriding a plugin, and I don't want them to, I can just remove them..?
