### ISSUE TITLE
Charset problem

### ISSUE THREAD

**Issue by fasatron** [zeit/hyper#843]
question marks instead of Cyrillic https://i.imgsafe.org/bdeba454fa.jpeg. OS: Linux Mint 18 64-bit

**Comment by jamox** [comment]
Does the font used support these characters?

**Comment by fasatron** [comment]
jamox, yes

**Comment by tmnsun** [comment]
I think this is related to issue https://github.com/zeit/hyper/issues/360

just check `locale -a` in hyper and in another terminal

In my case I have **RU.UTF-8** in hyper instead of **ru_RU.UTF-8**. So I add proper locale variables into .zshrc like so:

LANG=ru_RU.UTF-8
LC_CTYPE=ru_RU.UTF-8
LC_NUMERIC=ru_RU.UTF-8
LC_TIME=ru_RU.UTF-8
LC_COLLATE=ru_RU.UTF-8
LC_MONETARY=ru_RU.UTF-8
LC_MESSAGES=ru_RU.UTF-8
LC_PAPER=ru_RU.UTF-8
LC_NAME=ru_RU.UTF-8
LC_ADDRESS=ru_RU.UTF-8
LC_TELEPHONE=ru_RU.UTF-8
LC_MEASUREMENT=ru_RU.UTF-8
LC_IDENTIFICATION=ru_RU.UTF-8
LC_ALL=ru_RU.UTF-8

**Comment by tmnsun** [comment]
I did some tests and actually you need only two of these lines

LANG=ru_RU.UTF-8
LC_CTYPE=ru_RU.UTF-8
