### ISSUE TITLE
URL Parsing error: Type git@github.com:zeit/hyper.git and Hyper crashes

### ISSUE THREAD

**Issue by bnb** [zeit/hyper#867]
If you just run 

```bash
$ git@github.com:zeit/hyper.git
```

Hyper crashes. I assume this is because it is trying to parse the "command" as a URL. 

Explored a bit:

Running `git@github.com` opens GitHub.com up just fine.

Running `git@github.com:` opens GitHub.com up, but it was delayed a little bit - this could have quite possibly been my connection, though.

Running `git@github.com:zeit`crashes the terminal - this is the origin of the issue, as I don't think anything is expected after the `:`.

**Comment by oliverdunk** [comment]
The issue is that domainRegex reads this as a valid URL, and so the domain command parser tries to navigate to it. However, chromium does not support URLs with authentication and so the page simply crashes.

`/\b((?=[a-z0-9-]{1,63}\.)(xn--)?[a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,63}\b|^localhost$|^127(?:\.[0-9]+){0,2}\.[0-9]+$|^(?:0*:)*?:?0*1$/` is the regex being used.

I will try to fix this in a PR by only allowing URLs without the ':' character.

**Comment by oliverdunk** [comment]
To elaborate, the naive thing the client does is assuming that if the URL matches the domainRegex, the correct URL to navigate to must be everything until a path is reached.
